// src/components/communication/WhatsAppCommunicationPreview.jsx

import React, { useState, useEffect } from 'react';
import { Button } from '../ui/Button'; // Assuming a generic Button component exists
import toast from 'react-hot-toast'; // For user feedback
import { Modal } from '../ui/Modal';
import { communicationEngine } from '../../services/communication/communicationEngine';
import { whatsappShareAdapter } from '../../services/communication/whatsappShareAdapter';

/**
 * Premium WhatsApp Communication Preview & Share flow.
 * Consumes the exact payload generated by communicationEngine.prepareCommunication.
 *
 * Props:
 *   workspaceId, userId, invoiceId – identifiers required to build the payload.
 *   onClose – callback when the preview modal is dismissed.
 */
export default function WhatsAppCommunicationPreview({ workspaceId, userId, invoiceId, onClose }) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [payload, setPayload] = useState(null);
  const [editableMessage, setEditableMessage] = useState('');

  // Prepare the communication payload once on mount
  useEffect(() => {
    const prepare = async () => {
      try {
        if (!navigator.onLine) {
          throw new Error('Network offline – cannot prepare WhatsApp communication');
        }
        const comm = await communicationEngine.prepareCommunication({
          workspaceId,
          userId,
          invoiceId,
          overrides: {}
        });
        setPayload(comm);
        setEditableMessage(comm.message);
      } catch (e) {
        console.error(e);
        setError(e.message);
      } finally {
        setLoading(false);
      }
    };
    prepare();
  }, [workspaceId, userId, invoiceId]);

  const openWhatsApp = async () => {
  if (!payload) return;
  // Demo mode guard
  if (localStorage.getItem('billqyro_demo_session_active') === 'true') {
    toast.error('WhatsApp sharing is disabled in Demo mode.');
    return;
  }
  setLoading(true);
  try {
    const result = await whatsappShareAdapter.shareViaWhatsApp({
      recipient: payload.recipientPhone,
      message: editableMessage,
      attachments: payload.attachments
    });
    console.log('[WhatsAppCommunicationPreview] share result', result);
    toast.success('WhatsApp opened');
  } catch (e) {
    console.error(e);
    setError(e.message);
    toast.error(e.message);
  } finally {
    setLoading(false);
  }
};

  const downloadPdf = () => {
    if (!payload || !payload.attachments) return;
    const pdf = payload.attachments.find(a => a.type === 'pdf');
    if (pdf && pdf.blob) {
      const link = document.createElement('a');
      link.href = pdf.blobUrl || URL.createObjectURL(pdf.blob);
      link.download = pdf.name || 'invoice.pdf';
      link.click();
    }
  };

  // UI rendering
  return (
    <Modal isOpen={true} onClose={onClose} title="WhatsApp Reminder Preview">
        {error && <p className="text-red-600 mb-2">Error: {error}</p>}
        {loading && <p className="mb-2">Loading…</p>}
{payload && (
          <>
            <div className="grid grid-cols-2 gap-2 mb-4 text-sm text-gray-700 dark:text-gray-300">
              <div><strong>Customer:</strong> {payload.customer?.name || ''}</div>
              <div><strong>Customer ID:</strong> {payload.customer?.id || ''}</div>
              <div><strong>Invoice #:</strong> {payload.invoice?.invoiceNumber || ''}</div>
              <div><strong>Total:</strong> {payload.invoice?.grandTotal ?? ''}</div>
              <div><strong>Paid:</strong> {payload.invoice?.amountPaid ?? ''}</div>
              <div><strong>Due:</strong> {payload.invoice?.balanceDue ?? ''}</div>
              <div><strong>Due Date:</strong> {payload.invoice?.dueDate ?? ''}</div>
              {payload.attachments?.some(a => a.type === 'pdf') && (
                (() => {
                  const pdf = payload.attachments.find(a => a.type === 'pdf');
                  return pdf.ready ? (
                    <div className="col-span-2 text-green-600">PDF: Ready</div>
                  ) : (
                    <div className="col-span-2 text-red-600">PDF: Failed</div>
                  );
                })()
              )}
              {payload.attachments?.some(a => a.type === 'image') && (
                (() => {
                  const img = payload.attachments.find(a => a.type === 'image');
                  return img.ready ? (
                    <div className="col-span-2 text-green-600">Business Image: Ready</div>
                  ) : (
                    <div className="col-span-2 text-red-600">Business Image: Failed</div>
                  );
                })()
              )}
              {payload.portalLink && (
                <div className="col-span-2 text-green-600">Customer Portal Link: Enabled</div>
              )}
            </div>
            <div className="border rounded p-3 mb-4 bg-gray-50 dark:bg-gray-700">
              <textarea
                className="w-full h-32 p-2 border rounded"
                value={editableMessage}
                onChange={(e) => setEditableMessage(e.target.value)}
                disabled={loading}
              />
            </div>
            <div className="flex justify-end space-x-2">
              <Button onClick={onClose} disabled={loading}>Cancel</Button>
              <Button onClick={() => setEditableMessage(prev => prompt('Edit Message', prev) || prev)} disabled={loading}>Edit</Button>
              {payload.attachments?.some(a => a.type === 'pdf') && (
                <Button onClick={downloadPdf} disabled={loading || !(payload.attachments.find(a => a.type === 'pdf')?.ready)}>Download PDF</Button>
              )}
              <Button onClick={openWhatsApp} disabled={loading}>Open WhatsApp</Button>
            </div>
          </>
        )}
      </Modal>
  );
}
