import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowRight, CheckCircle2, ShieldCheck, TrendingUp, Sparkles, Download, Link2, Smartphone, CreditCard, ChevronDown, Zap, Lock, RefreshCw, Layers, Scissors, Stethoscope, GraduationCap, Wrench, ShoppingBag, BarChart3, ArrowUpRight } from 'lucide-react';
import Logo from '../components/Logo';
import Login from './Login';
import CustomerPortalLogin from '../components/portal/CustomerPortalLogin';
import HeroBackground from '../components/HeroBackground';
import ScrollReveal from '../components/ScrollReveal';
import { AnimatedThemeToggler } from '../components/AnimatedThemeToggler';
import { useTheme } from '../contexts/ThemeContext';

const Landing = ({ onLoginSuccess }) => {
  const { isDarkMode } = useTheme();
  const [faqOpen, setFaqOpen] = useState(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);
  const [portalMode, setPortalMode] = useState('business');
  useEffect(() => { const onScroll = () => setIsScrolled(window.scrollY > 18); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll); }, []);
  const scrollTo = (id) => { const el = document.getElementById(id); if (el) window.scrollTo({ top: window.scrollY + el.getBoundingClientRect().top - 90, behavior: 'smooth' }); setMobileMenuOpen(false); };
  const categories = [[ShoppingBag,'Retail & Supermarket','Inventory, POS-ready billing and stock-aware invoices.'],[Scissors,'Tailoring & Boutiques','Measurements, custom orders, advances and delivery tracking.'],[Stethoscope,'Clinics & Healthcare','Patient ledgers, consultation billing and secure records.'],[Wrench,'Repair & Electronics','Job sheets, parts, labour and warranty-ready billing.'],[GraduationCap,'Coaching & Education','Student directories, monthly dues and payment receipts.']];
  const faqs = [['Does BillQyro work offline?','Yes. BillQyro is designed around a local-first architecture so invoices, customers and core workflows remain usable offline and synchronize when connectivity returns.'],['Can customers view an invoice without an account?','Yes. Every invoice can have a secure Live Link so a customer can view the document and follow the configured payment workflow from a browser.'],['Can I change the brand theme?','Yes. The platform uses a semantic theme system, allowing the accent and visual language to adapt without rewriting the application UI.'],['Is my workspace data isolated?','Yes. Workspace-aware storage and authenticated synchronization keep business data separated across workspaces.']];
  const featureData = [[Zap,'Fast invoicing','Create polished invoices, estimates and receipts with a focused workflow.'],[Link2,'Live invoice links','Give customers a beautiful browser-based invoice experience.'],[CreditCard,'Payments & collections','Track paid, partial, unpaid and overdue balances with confidence.'],[ShieldCheck,'Secure by design','Workspace isolation, authentication and controlled data access.'],[RefreshCw,'Offline-first','Keep working during connectivity gaps and synchronize later.'],[Download,'PDF-ready','Generate professional documents for print, download and sharing.']];
  return <div className={`billqyro-landing-premium min-h-screen overflow-x-hidden bg-theme-app text-theme-primary ${isDarkMode?'dark':''}`}>
    <div className="fixed inset-0 -z-10 pointer-events-none overflow-hidden"><div className="absolute left-1/2 top-[-260px] h-[620px] w-[900px] -translate-x-1/2 rounded-full bg-theme-accent/10 blur-[120px]"/><div className="absolute right-[-180px] top-[38%] h-[420px] w-[420px] rounded-full bg-theme-accent/5 blur-[100px]"/><HeroBackground/></div>
    <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-500 ${isScrolled?'border-b border-theme-border-soft bg-theme-app/85 shadow-xl backdrop-blur-2xl':'bg-transparent'}`}><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><button onClick={()=>scrollTo('top')} className="shrink-0"><Logo type="horizontal" forceWhiteText={false}/></button><nav className="hidden items-center gap-1 rounded-full border border-theme-border-soft bg-theme-card/70 p-1 backdrop-blur-xl md:flex">{['features','categories','workflow','faq'].map(item=><button key={item} onClick={()=>scrollTo(item)} className="rounded-full px-4 py-2 text-xs font-bold capitalize text-theme-muted transition hover:bg-theme-accent/10 hover:text-theme-primary">{item}</button>)}</nav><div className="flex items-center gap-2"><AnimatedThemeToggler/><button onClick={()=>scrollTo('login')} className="hidden rounded-full bg-theme-accent px-5 py-2.5 text-xs font-extrabold text-white shadow-lg shadow-theme-accent/20 transition hover:-translate-y-0.5 sm:block">Sign in</button><button onClick={()=>setMobileMenuOpen(v=>!v)} className="rounded-xl border border-theme-border-soft bg-theme-card p-2.5 md:hidden"><Layers size={18}/></button></div></div><AnimatePresence>{mobileMenuOpen&&<motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} className="border-t border-theme-border-soft bg-theme-app/95 px-5 py-4 backdrop-blur-xl md:hidden">{['features','categories','workflow','faq','login'].map(item=><button key={item} onClick={()=>scrollTo(item)} className="block w-full border-b border-theme-border-soft py-3 text-left text-sm font-bold capitalize">{item}</button>)}</motion.div>}</AnimatePresence></header>
    <main id="top" className="pt-28">
      <section className="relative flex min-h-[720px] items-center justify-center text-center"><div className="mx-auto max-w-6xl px-5"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="mb-7 inline-flex items-center gap-2 rounded-full border border-theme-accent/20 bg-theme-accent/5 px-4 py-2 text-xs font-extrabold text-theme-accent"><Sparkles size={14}/> Modern billing. Premium control.</motion.div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.1,duration:.8}} className="mx-auto max-w-5xl font-[Sora] text-5xl font-black tracking-[-.055em] sm:text-6xl lg:text-8xl">Billing that looks as <span className="bg-gradient-to-r from-theme-accent via-theme-primary to-theme-accent bg-clip-text text-transparent">premium</span> as your business.</motion.h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.2,duration:.7}} className="mx-auto mt-7 max-w-2xl text-base leading-8 text-theme-muted sm:text-lg">BillQyro brings invoices, payments, customers, live links, analytics and business workflows into one refined command center.</motion.p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={()=>scrollTo('login')} className="group inline-flex items-center justify-center gap-2 rounded-2xl bg-theme-accent px-7 py-4 text-sm font-black text-white shadow-2xl shadow-theme-accent/25 transition hover:-translate-y-1">Start Billing <ArrowRight size={17} className="transition group-hover:translate-x-1"/></button><button onClick={()=>scrollTo('preview')} className="inline-flex items-center justify-center gap-2 rounded-2xl border border-theme-border-soft bg-theme-card/70 px-7 py-4 text-sm font-black backdrop-blur-xl transition hover:-translate-y-1"><BarChart3 size={17}/> Explore platform</button></div><div className="mx-auto mt-9 flex max-w-2xl flex-wrap justify-center gap-x-7 gap-y-3 text-[11px] font-bold text-theme-muted">{['Offline-first','Secure workspace','Live invoice links','Premium themes'].map(x=><span key={x} className="inline-flex items-center gap-1.5"><CheckCircle2 size={14} className="text-theme-accent"/>{x}</span>)}</div></div></section>
      <section id="preview" className="py-8"><ScrollReveal><div className="relative overflow-hidden rounded-[32px] border border-theme-border-soft bg-theme-card/80 p-2 shadow-[0_35px_100px_rgba(15,23,42,.12)] backdrop-blur-xl"><div className="rounded-[26px] border border-theme-border-soft bg-theme-app p-5 sm:p-7"><div className="flex items-center justify-between border-b border-theme-border-soft pb-5"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-theme-muted">Financial command center</p><h2 className="mt-1 text-xl font-black sm:text-2xl">Your business, at a glance.</h2></div><div className="hidden rounded-full bg-theme-accent/10 px-3 py-1.5 text-[10px] font-black text-theme-accent sm:block">LIVE SYNC</div></div><div className="grid gap-4 py-6 sm:grid-cols-3">{[['Revenue','₹ 2,48,650','+18.4%'],['Collected','₹ 1,86,420','+12.7%'],['Outstanding','₹ 62,230','12 invoices']].map(([a,b,c])=><div key={a} className="rounded-2xl border border-theme-border-soft bg-theme-card p-5"><p className="text-xs font-bold text-theme-muted">{a}</p><p className="mt-2 text-2xl font-black tracking-tight">{b}</p><p className="mt-2 text-[10px] font-black text-theme-accent">{c}</p></div>)}</div><div className="grid gap-4 lg:grid-cols-[1.4fr_.6fr]"><div className="rounded-2xl border border-theme-border-soft bg-theme-card p-5"><div className="mb-5 flex items-center justify-between"><span className="text-sm font-black">Revenue performance</span><TrendingUp size={18} className="text-theme-accent"/></div><div className="flex h-40 items-end gap-2">{[35,48,42,65,58,74,69,88,78,94,82,100].map((h,i)=><div key={i} className="flex-1 rounded-t-lg bg-theme-accent/20 transition hover:bg-theme-accent/50" style={{height:`${h}%`}}/>)}</div></div><div className="rounded-2xl border border-theme-border-soft bg-theme-card p-5"><p className="text-sm font-black">Collection health</p><div className="mx-auto my-6 flex h-32 w-32 items-center justify-center rounded-full border-[12px] border-theme-accent/15 border-t-theme-accent"><div className="text-center"><b className="text-2xl">76%</b><span className="block text-[9px] font-bold text-theme-muted">COLLECTED</span></div></div></div></div></div></div></ScrollReveal></section>
      <section id="features" className="py-16"><div className="mx-auto max-w-3xl text-center"><span className="text-[10px] font-black uppercase tracking-[.25em] text-theme-accent">One platform</span><h2 className="mt-3 text-4xl font-black sm:text-5xl">Everything important. Nothing noisy.</h2><p className="mt-5 text-theme-muted">Designed for businesses that want serious financial control without a complicated interface.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{featureData.map(([Icon,title,desc])=><motion.div whileHover={{y:-5}} key={title} className="rounded-3xl border border-theme-border-soft bg-theme-card/75 p-7 shadow-sm backdrop-blur-xl"><div className="mb-6 flex h-11 w-11 items-center justify-center rounded-2xl bg-theme-accent/10 text-theme-accent"><Icon size={20}/></div><h3 className="text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-theme-muted">{desc}</p></motion.div>)}</div></section>
      <section id="categories" className="py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><span className="text-[10px] font-black uppercase tracking-[.25em] text-theme-accent">Built around you</span><h2 className="mt-3 text-4xl font-black">Made for real businesses.</h2></div><p className="max-w-md text-sm leading-7 text-theme-muted">Start with a general workflow and shape the experience around your business category.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{categories.map(([Icon,title,desc])=><motion.div whileHover={{y:-4}} key={title} className="group rounded-3xl border border-theme-border-soft bg-theme-card p-6 transition hover:border-theme-accent/30"><div className="flex items-center justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-theme-accent/10 text-theme-accent"><Icon size={22}/></div><ArrowUpRight size={18} className="text-theme-muted transition group-hover:text-theme-accent"/></div><h3 className="mt-6 font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-theme-muted">{desc}</p></motion.div>)}</div></section>
      <section id="workflow" className="py-16"><div className="rounded-[32px] border border-theme-border-soft bg-theme-card/60 p-7 sm:p-12"><div className="max-w-2xl"><span className="text-[10px] font-black uppercase tracking-[.25em] text-theme-accent">Simple operating rhythm</span><h2 className="mt-3 text-4xl font-black">From invoice to collected cash.</h2></div><div className="mt-12 grid gap-8 md:grid-cols-4">{[['01','Create','Build the invoice in seconds.'],['02','Share','Send PDF or Live Link.'],['03','Collect','Record payments and proofs.'],['04','Reconcile','See the ledger and reports.']].map(([n,t,d])=><div key={n}><span className="text-xs font-black text-theme-accent">{n}</span><div className="my-4 h-px bg-theme-border-soft"/><h3 className="font-black">{t}</h3><p className="mt-2 text-sm leading-6 text-theme-muted">{d}</p></div>)}</div></div></section>
      <section id="security" className="py-16"><div className="grid gap-4 lg:grid-cols-3">{[[Lock,'Private workspaces'],[ShieldCheck,'Controlled access'],[Smartphone,'Works everywhere']].map(([Icon,title])=><div key={title} className="flex items-center gap-4 rounded-2xl border border-theme-border-soft bg-theme-card p-5"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-theme-accent/10 text-theme-accent"><Icon size={19}/></div><div><h3 className="text-sm font-black">{title}</h3><p className="mt-1 text-xs text-theme-muted">Built into the platform.</p></div></div>)}</div></section>
      <section id="faq" className="py-16"><div className="mx-auto max-w-3xl"><div className="text-center"><span className="text-[10px] font-black uppercase tracking-[.25em] text-theme-accent">Questions</span><h2 className="mt-3 text-4xl font-black">Frequently asked.</h2></div><div className="mt-10 divide-y divide-theme-border-soft rounded-3xl border border-theme-border-soft bg-theme-card">{faqs.map(([q,a],i)=><div key={q}><button onClick={()=>setFaqOpen(faqOpen===i?null:i)} className="flex w-full items-center justify-between gap-5 p-6 text-left text-sm font-black"><span>{q}</span><ChevronDown size={18} className={`shrink-0 transition ${faqOpen===i?'rotate-180 text-theme-accent':''}`}/></button><AnimatePresence>{faqOpen===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><p className="px-6 pb-6 text-sm leading-7 text-theme-muted">{a}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>
      <section id="login" className="py-16"><div className="mx-auto max-w-5xl overflow-hidden rounded-[32px] border border-theme-accent/15 bg-theme-card shadow-[0_35px_100px_rgba(15,23,42,.12)]"><div className="border-b border-theme-border-soft bg-theme-accent/[.04] p-7 text-center sm:p-10"><span className="text-[10px] font-black uppercase tracking-[.25em] text-theme-accent">Secure access</span><h2 className="mt-3 text-3xl font-black">Enter your BillQyro workspace.</h2><p className="mx-auto mt-3 max-w-xl text-sm text-theme-muted">Business owners can sign in to manage billing. Customers can access their invoice portal separately.</p><div className="mx-auto mt-7 flex max-w-md rounded-xl border border-theme-border-soft bg-theme-app p-1"><button onClick={()=>setPortalMode('business')} className={`flex-1 rounded-lg py-2.5 text-xs font-black ${portalMode==='business'?'bg-theme-accent text-white shadow-md':'text-theme-muted'}`}>Business Login / Register</button><button onClick={()=>setPortalMode('customer')} className={`flex-1 rounded-lg py-2.5 text-xs font-black ${portalMode==='customer'?'bg-theme-accent text-white shadow-md':'text-theme-muted'}`}>Customer Portal</button></div></div><div className="p-6 sm:p-10">{portalMode==='business'?<Login onLoginSuccess={onLoginSuccess}/>:<CustomerPortalLogin onVerificationSuccess={(id,phone)=>{sessionStorage.setItem('billqyro_customer_portal_id',id);sessionStorage.setItem('billqyro_customer_portal_phone',phone);window.location.href=`/customer/${id}`;}}/>}</div></div></section>
    </main>
    <footer className="border-t border-theme-border-soft bg-theme-app px-6 py-10"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 sm:flex-row"><div className="flex items-center gap-3"><Logo type="horizontal" forceWhiteText={false}/><span className="text-[10px] font-bold text-theme-muted">© 2026 BillQyro Platform</span></div><div className="flex flex-wrap justify-center gap-5 text-xs font-bold text-theme-muted"><button onClick={()=>scrollTo('faq')} className="hover:text-theme-accent">Help</button><button onClick={()=>scrollTo('login')} className="hover:text-theme-accent">Sign In</button><span>Premium Billing Platform</span></div></div></footer>
  </div>;
};
export default Landing;
