import { generateSmartDemoData } from './demoDataGenerator';
import { toast } from 'react-hot-toast';

const KEYS = {
  CUSTOMERS: 'billqyro_demo_customers',
  PRODUCTS: 'billqyro_demo_products',
  INVOICES: 'billqyro_demo_invoices',
  PAYMENTS: 'billqyro_demo_payments',
  REPORTS: 'billqyro_demo_reports',
  SESSION_ACTIVE: 'billqyro_demo_session_active',
  SESSION_PERSONA: 'billqyro_demo_session_persona',
  SETTINGS: 'billqyro_demo_settings',
  ADMIN_DATA: 'billqyro_demo_admin_data'
};

export const isDemoModeActive = () => {
  return localStorage.getItem(KEYS.SESSION_ACTIVE) === 'true';
};

export const getDemoCustomers = () => {
  try {
    return JSON.parse(localStorage.getItem(KEYS.CUSTOMERS)) || [];
  } catch { return []; }
};

export const getDemoProducts = () => {
  try {
    return JSON.parse(localStorage.getItem(KEYS.PRODUCTS)) || [];
  } catch { return []; }
};

export const getDemoInvoices = () => {
  try {
    return JSON.parse(localStorage.getItem(KEYS.INVOICES)) || [];
  } catch { return []; }
};

export const getDemoPayments = () => {
  try {
    return JSON.parse(localStorage.getItem(KEYS.PAYMENTS)) || [];
  } catch { return []; }
};

export const getDemoReports = () => {
  try {
    return JSON.parse(localStorage.getItem(KEYS.REPORTS)) || {};
  } catch { return {}; }
};

export const saveDemoInvoice = (invoice) => {
  const invoices = getDemoInvoices();
  const existingIndex = invoices.findIndex(i => i.id === invoice.id);
  if (existingIndex >= 0) invoices[existingIndex] = invoice;
  else invoices.push(invoice);
  
  // Keep sorted descending
  invoices.sort((a, b) => new Date(b.date) - new Date(a.date));
  localStorage.setItem(KEYS.INVOICES, JSON.stringify(invoices));
  
  // Also recalculate reports
  recalculateDemoReports(invoices);
  window.dispatchEvent(new Event('storage'));
};

export const deleteDemoInvoice = (invoiceId) => {
  const invoices = getDemoInvoices().filter(i => i.id !== invoiceId);
  localStorage.setItem(KEYS.INVOICES, JSON.stringify(invoices));
  recalculateDemoReports(invoices);
  window.dispatchEvent(new Event('storage'));
};

export const saveDemoCustomer = (customer) => {
  const customers = getDemoCustomers();
  const existingIndex = customers.findIndex(c => c.id === customer.id);
  if (existingIndex >= 0) customers[existingIndex] = customer;
  else customers.push(customer);
  
  localStorage.setItem(KEYS.CUSTOMERS, JSON.stringify(customers));
  window.dispatchEvent(new Event('storage'));
};

export const saveDemoProduct = (product) => {
  const products = getDemoProducts();
  const existingIndex = products.findIndex(p => p.id === product.id);
  if (existingIndex >= 0) products[existingIndex] = product;
  else products.push(product);
  
  localStorage.setItem(KEYS.PRODUCTS, JSON.stringify(products));
  window.dispatchEvent(new Event('storage'));
};

export const clearDemoData = () => {
  Object.values(KEYS).forEach(key => {
    localStorage.removeItem(key);
  });
  window.dispatchEvent(new Event('storage'));
};

const recalculateDemoReports = (invoices) => {
  let totalSales = 0, pendingDue = 0, paidAmount = 0;
  invoices.forEach(inv => {
    totalSales += (inv.grandTotal || 0);
    paidAmount += (inv.amountPaid || 0);
    pendingDue += (inv.balanceDue || 0);
  });
  
  const customers = getDemoCustomers();
  
  const reportsPayload = {
    totalSales, pendingDue, paidAmount,
    customerCount: customers.length, 
    invoiceCount: invoices.length,
    generatedAt: new Date().toISOString()
  };
  localStorage.setItem(KEYS.REPORTS, JSON.stringify(reportsPayload));
};

export const autoGenerateDemoDataIfNeeded = () => {
  if (!isDemoModeActive()) return;
  const invoices = getDemoInvoices();
  if (invoices.length === 0) {
    const persona = localStorage.getItem(KEYS.SESSION_PERSONA) || 'General';
    const { products, customers, invoices: newInvoices, payments } = generateSmartDemoData(persona);
    
    localStorage.setItem(KEYS.PRODUCTS, JSON.stringify(products));
    localStorage.setItem(KEYS.CUSTOMERS, JSON.stringify(customers));
    localStorage.setItem(KEYS.INVOICES, JSON.stringify(newInvoices));
    localStorage.setItem(KEYS.PAYMENTS, JSON.stringify(payments));
    
    recalculateDemoReports(newInvoices);
    
    toast.success('Smart demo data generated', { icon: '🧪' });
    window.dispatchEvent(new Event('storage'));
  }
};

export const generateFakeAdminData = () => {
  const adminData = {
    totalUsers: 500,
    premiumUsers: 120,
    pendingPayments: 85,
    lockedUsers: 30,
    premiumRequests: 40,
    paymentProofs: 25,
    fakeRevenue: 1245000,
    fakePayPerBillRevenue: 45000,
    fakePremiumRevenue: 1200000,
    fakePendingPlatformDue: 15000,
    fakeApprovedPayments: 450,
    fakeRejectedPayments: 12,
    appHealth: {
      activeUsers: '2,500',
      syncStatus: '99.9%',
      errors: '3'
    }
  };
  localStorage.setItem(KEYS.ADMIN_DATA, JSON.stringify(adminData));
  window.dispatchEvent(new Event('storage'));
  return adminData;
};

export const getFakeAdminData = () => {
  try {
    return JSON.parse(localStorage.getItem(KEYS.ADMIN_DATA)) || null;
  } catch {
    return null;
  }
};
