import { jsPDF } from 'jspdf';
import { toast } from 'react-hot-toast';
import { calculateCanonicalInvoiceFinancials } from './invoiceMath';

let generating = false;

const clean = (value, fallback = '') => {
  if (value == null) return fallback;
  const text = String(value).replace(/[\u{1F300}-\u{1FAFF}\u2600-\u27BF]/gu, '').trim();
  return text || fallback;
};

const money = (value, currency = 'INR') => {
  const amount = Number(value) || 0;
  const symbol = currency === 'INR' ? 'Rs.' : currency === 'USD' ? '$' : currency === 'EUR' ? 'EUR' : currency;
  return `${symbol} ${amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const normalize = (invoice, settings = {}) => {
  const items = Array.isArray(invoice?.items) ? invoice.items : [];
  const normalizedItems = items.map((item, index) => {
    const qty = Number(item?.qty ?? item?.quantity ?? 1) || 0;
    const rate = Number(item?.rate ?? item?.price ?? item?.unitPrice ?? 0) || 0;
    const discount = Number(item?.discount ?? 0) || 0;
    const amount = Number(item?.amount ?? item?.total ?? (qty * rate - discount)) || 0;
    return {
      name: clean(item?.name || item?.description || item?.itemService || item?.title, `Item ${index + 1}`),
      qty,
      rate,
      discount,
      amount,
    };
  });

  return {
    invoice,
    settings,
    items: normalizedItems,
    businessName: clean(settings?.businessName || settings?.name, 'BillQyro Business'),
    customerName: clean(invoice?.customerName || invoice?.customer?.name || invoice?.client?.name, 'Walk-in Customer'),
    customerPhone: clean(invoice?.customerPhone || invoice?.customer?.phone || invoice?.client?.phone),
    customerEmail: clean(invoice?.customerEmail || invoice?.customer?.email || invoice?.client?.email),
    customerAddress: clean(invoice?.customerAddress || invoice?.customer?.address || invoice?.client?.address),
    invoiceNumber: clean(invoice?.invoiceNumber || invoice?.number, '000'),
    date: clean(invoice?.invoiceDate || invoice?.date || invoice?.createdAt, new Date().toLocaleDateString('en-IN')),
    currency: settings?.currencyCode || invoice?.currencyCode || 'INR',
  };
};

const drawHeader = (doc, data, pageWidth, margin) => {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(19);
  doc.setTextColor(20, 35, 48);
  doc.text(data.businessName, margin, 40);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 110, 120);
  const address = clean(data.settings?.address);
  const phone = clean(data.settings?.phone);
  if (address) doc.text(address, margin, 55, { maxWidth: 270 });
  if (phone) doc.text(`Phone: ${phone}`, margin, address ? 68 : 55);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(0, 150, 120);
  doc.text('INVOICE', pageWidth - margin, 40, { align: 'right' });
  doc.setFontSize(9);
  doc.setTextColor(80, 90, 100);
  doc.text(`#${data.invoiceNumber}`, pageWidth - margin, 55, { align: 'right' });
  doc.text(`Date: ${data.date}`, pageWidth - margin, 68, { align: 'right' });

  doc.setDrawColor(225, 230, 234);
  doc.line(margin, 82, pageWidth - margin, 82);
};

const drawCustomer = (doc, data, margin, y, pageWidth) => {
  doc.setFillColor(247, 249, 250);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 62, 4, 4, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(0, 130, 105);
  doc.text('BILL TO', margin + 12, y + 16);
  doc.setFontSize(12);
  doc.setTextColor(25, 35, 45);
  doc.text(data.customerName, margin + 12, y + 32);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(90, 100, 110);
  const details = [data.customerPhone, data.customerEmail, data.customerAddress].filter(Boolean).join('  |  ');
  if (details) doc.text(details, margin + 12, y + 47, { maxWidth: pageWidth - margin * 2 - 24 });
};

const drawFooter = (doc, pageWidth, pageHeight, margin) => {
  const page = doc.internal.getNumberOfPages();
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(140, 145, 150);
  doc.text('Generated by BillQyro', margin, pageHeight - 24);
  doc.text(`Page ${page}`, pageWidth - margin, pageHeight - 24, { align: 'right' });
};

const drawTableHeader = (doc, margin, y, width) => {
  doc.setFillColor(0, 150, 120);
  doc.rect(margin, y, width, 26, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('ITEM / DESCRIPTION', margin + 8, y + 17);
  doc.text('QTY', margin + width - 190, y + 17, { align: 'right' });
  doc.text('RATE', margin + width - 120, y + 17, { align: 'right' });
  doc.text('AMOUNT', margin + width - 8, y + 17, { align: 'right' });
};

export const generateInvoicePdfBlob = async (invoice, businessSettings = {}) => {
  if (!invoice) throw new Error('Invoice data is missing.');

  // Deliberately use jsPDF instead of React-PDF. React-PDF was the source of
  // the 20–45 second hangs on larger invoices.
  const data = normalize(invoice, businessSettings);
  const financials = calculateCanonicalInvoiceFinancials(invoice);
  const doc = new jsPDF({ unit: 'pt', format: 'a4', compress: true });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  drawHeader(doc, data, pageWidth, margin);
  drawCustomer(doc, data, margin, 98, pageWidth);

  let y = 178;
  drawTableHeader(doc, margin, y, contentWidth);
  y += 26;

  data.items.forEach((item, index) => {
    const nameLines = doc.splitTextToSize(item.name, contentWidth - 230);
    const rowHeight = Math.max(28, nameLines.length * 12 + 12);
    if (y + rowHeight > pageHeight - 100) {
      drawFooter(doc, pageWidth, pageHeight, margin);
      doc.addPage();
      y = 45;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(25, 35, 45);
      doc.text(`Invoice #${data.invoiceNumber} — continued`, margin, y);
      y += 20;
      drawTableHeader(doc, margin, y, contentWidth);
      y += 26;
    }

    if (index % 2 === 1) {
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, y, contentWidth, rowHeight, 'F');
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(35, 45, 55);
    doc.text(nameLines, margin + 8, y + 18);
    doc.text(String(item.qty), margin + contentWidth - 190, y + 18, { align: 'right' });
    doc.text(money(item.rate, data.currency), margin + contentWidth - 120, y + 18, { align: 'right' });
    doc.setFont('helvetica', 'bold');
    doc.text(money(item.amount, data.currency), margin + contentWidth - 8, y + 18, { align: 'right' });
    doc.setDrawColor(235, 238, 240);
    doc.line(margin, y + rowHeight, margin + contentWidth, y + rowHeight);
    y += rowHeight;
  });

  const totalsHeight = 132;
  if (y + totalsHeight > pageHeight - 55) {
    drawFooter(doc, pageWidth, pageHeight, margin);
    doc.addPage();
    y = 55;
  } else {
    y += 18;
  }

  const boxX = pageWidth - margin - 245;
  const boxW = 245;
  doc.setFillColor(247, 249, 250);
  doc.roundedRect(boxX, y, boxW, totalsHeight, 4, 4, 'F');

  const line = (label, value, yy, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(bold ? 11 : 9);
    doc.setTextColor(bold ? 20 : 80, bold ? 35 : 90, bold ? 45 : 100);
    doc.text(label, boxX + 12, yy);
    doc.text(value, boxX + boxW - 12, yy, { align: 'right' });
  };

  line('Subtotal', money(financials.subtotal, data.currency), y + 23);
  if (financials.discountAmount) line('Discount', `- ${money(financials.discountAmount, data.currency)}`, y + 43);
  if (financials.taxAmount) line('Tax', money(financials.taxAmount, data.currency), y + 63);
  if (financials.shipping) line('Shipping', money(financials.shipping, data.currency), y + 83);
  line('Grand Total', money(financials.currentInvoiceTotal, data.currency), y + 103, true);
  line('Paid', money(financials.amountPaid, data.currency), y + 123);

  y += totalsHeight + 18;
  if (financials.balanceDue > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(205, 55, 70);
    doc.text(`Balance Due: ${money(financials.balanceDue, data.currency)}`, margin, y);
  } else {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(0, 140, 110);
    doc.text('PAID IN FULL', margin, y);
  }

  const payment = invoice?.paymentHistory?.length ? invoice.paymentHistory[invoice.paymentHistory.length - 1] : null;
  if (payment) {
    y += 18;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 105, 110);
    const paymentText = `Latest payment: ${money(payment.amount, data.currency)}${payment.method ? ` via ${clean(payment.method)}` : ''}`;
    doc.text(paymentText, margin, y);
  }

  drawFooter(doc, pageWidth, pageHeight, margin);
  return doc.output('blob');
};

export const downloadStableInvoicePDF = async (invoice, businessSettings = {}) => {
  if (!invoice || generating) return false;
  generating = true;
  const toastId = toast.loading('Generating PDF…');
  try {
    const blob = await generateInvoicePdfBlob(invoice, businessSettings);
    const url = URL.createObjectURL(blob);
    const number = clean(invoice?.invoiceNumber || '000').replace(/[^a-zA-Z0-9_-]/g, '_');
    const link = document.createElement('a');
    link.href = url;
    link.download = `Invoice_${number}.pdf`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 5000);
    toast.dismiss(toastId);
    toast.success('PDF downloaded');
    return true;
  } catch (error) {
    toast.dismiss(toastId);
    console.error('Fast PDF generation failed:', error);
    toast.error(error?.message || 'PDF তৈরি করা যায়নি।');
    return false;
  } finally {
    generating = false;
  }
};

export default downloadStableInvoicePDF;
