#!/usr/bin/env node
/**
 * Generate alpha (opacity) utility classes for theme-CSS-variable colors.
 *
 * Tailwind v3 cannot emit `bg-theme-surface/50`-style classes when the color
 * is defined as a plain `var(--x)` string (no RGB channel triplet), so these
 * utilities silently rendered with NO color at all. This script scans src/
 * for every full class token `[*:]*(bg|text|border)-theme-<name>/<alpha>`
 * actually used and emits color-mix based definitions (correct pseudo-class /
 * group / dark selectors) into src/styles/alphaUtilities.css.
 *
 * Re-run after adding new /<alpha> theme classes: node scripts/generateAlphaUtilities.cjs
 */
const fs = require('fs');
const path = require('path');

const SRC = path.resolve(__dirname, '..', 'src');
const OUT = path.resolve(__dirname, '..', 'src', 'styles', 'alphaUtilities.css');

// CSS variable for each Tailwind theme color name (must match tailwind.config.js).
const CSS_VAR = {
  app: '--app-bg', 'app-soft': '--app-bg-soft',
  surface: '--surface', 'surface-elevated': '--surface-elevated',
  'surface-hover': '--surface-hover',
  card: '--card-bg', main: '--app-bg',
  primary: '--text-primary', secondary: '--text-secondary', muted: '--text-muted',
  accent: '--accent', 'accent-strong': '--accent-strong', 'accent-light': '--accent-light',
  success: '--success', warning: '--warning', danger: '--danger', info: '--info',
  'border-soft': '--border-soft', 'border-strong': '--border-strong',
};
const PROP = { bg: 'background-color', text: 'color', border: 'border-color' };

function walk(dir, acc) {
  for (const f of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, f.name);
    if (f.isDirectory()) walk(p, acc);
    else if (/\.(jsx|js)$/.test(f.name)) acc.push(p);
  }
  return acc;
}

const files = walk(SRC, []);
const found = new Map(); // fullToken -> declaration
const tokenRe = /((?:[a-z-]+:)*)((?:bg|text|border)-theme-[a-z-]+\/\d+)/g;

for (const file of files) {
  const src = fs.readFileSync(file, 'utf8');
  let m;
  while ((m = tokenRe.exec(src))) {
    const prefixes = m[1] ? m[1].split(':').filter(Boolean) : [];
    const token = m[2];
    const [, prop, name, alpha] = token.match(/^(bg|text|border)-theme-([a-z-]+)\/(\d+)$/);
    if (!CSS_VAR[name] || !PROP[prop]) {
      console.warn(`  ! unknown color "${name}" in "${m[0]}" (${path.relative(SRC, file)})`);
      continue;
    }
    const decl = `${PROP[prop]}: color-mix(in srgb, var(${CSS_VAR[name]}) ${alpha}%, transparent);`;
    found.set(m[0], { prefixes, token, decl });
  }
}

const esc = (s) => s.replace(/([\\/.:])/g, '\\$1');
const buildSelector = (fullToken, prefixes) => {
  let sel = '.' + esc(fullToken);
  let wrapper = '';
  for (const p of prefixes) {
    if (p === 'dark') sel += ':is(.dark *)';
    else if (p === 'hover') sel += ':hover';
    else if (p === 'focus') sel += ':focus';
    else if (p === 'focus-visible') sel += ':focus-visible';
    else if (p === 'active') sel += ':active';
    else if (p === 'disabled') sel += ':disabled';
    else if (p === 'placeholder') sel += '::placeholder';
    else if (p === 'selection') sel += '::selection';
    else if (p === 'group-hover') wrapper = '.group:hover ';
    else { console.warn(`  ! unhandled prefix "${p}:" on ${fullToken}`); }
  }
  return wrapper + sel;
};

const lines = [];
for (const [fullToken, { prefixes, decl }] of [...found.entries()].sort()) {
  lines.push(`${buildSelector(fullToken, prefixes)} { ${decl} }`);
}

const css = `/* ==========================================================================
   AUTO-GENERATED by scripts/generateAlphaUtilities.cjs — DO NOT EDIT BY HAND.
   Tailwind v3 cannot generate /<alpha> variants for var()-based colors, so
   these translucent utilities are defined here with color-mix instead.
   One rule per class token exactly as used in src/ (pseudo/dark selectors
   preserved). Re-run the script after adding new theme /<alpha> classes.
   ========================================================================== */
${lines.join('\n')}
`;
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, css);
console.log(`Wrote ${OUT}: ${found.size} class tokens.`);
