import React, { useState, useEffect } from 'react';
import { isAdminUser } from './utils/adminAccess';
import { toast, Toaster } from 'react-hot-toast';
import { useThemeEngine } from './hooks/useThemeEngine';
import { AnimatePresence, motion } from 'framer-motion';
import { Lock, AlertTriangle, Trash2 } from 'lucide-react';
import { 
  getDemoInvoices, getDemoCustomers, getDemoProducts, getDemoPayments, getDemoReports, 
  saveDemoInvoice, deleteDemoInvoice, saveDemoCustomer, saveDemoProduct, isDemoModeActive,
  autoGenerateDemoDataIfNeeded
} from './utils/demoDataManager';
import Layout from './components/Layout';
import { calculateTotals } from './utils/invoiceUtils';
import { isEducationBusiness } from './config/businessPresets';

import PostLoginWelcome from './components/PostLoginWelcome';
import { invoiceSchema, customerSchema, validatePayload } from './utils/validation';
import ClassicLoader from './components/ClassicLoader';
import {
  getAuthSession,
  logout,
  getInvoices,
  saveInvoice,
  deleteInvoice,
  getCustomers,
  saveCustomer,
  deleteCustomer,
  getProducts,
  saveProduct,
  deleteProduct,
  getSettings,
  saveSettings,
  resetToDemoData,
  initializeStorage,
  getSubscriptionStatus,
  saveSubscriptionStatus,
  getExpenses,
  saveExpense,
  deleteExpense,
  importRestore,
  syncFromFirestore,
  getGlobalAdminSettings,
  getUserRevenueState,
  getActiveAnnouncement,
  getRealUserId
} from './services/dbEngine';
import { downloadInvoicePDF } from './utils/pdfUtils';
import { auth, firebaseReady } from './services/firebaseConfig';
import { onAuthStateChanged } from 'firebase/auth';
import { triggerSuccessFeedback } from './utils/feedback';
import { sendEmpireEvent, sendEmpireError, sendEmpireHealth } from './services/empireAgent';
import { collection, query, where, onSnapshot } from 'firebase/firestore';
import { db } from './services/firebaseConfig';
import QuickBillModal from './components/QuickBillModal';
import AdminPINLogin from './pages/admin/AdminPINLogin';
import Confetti from 'react-confetti';
import CommandPalette from './components/CommandPalette';
import { pageVariants } from './utils/animations';

const Landing = React.lazy(() => import('./pages/Landing'));
const Login = React.lazy(() => import('./pages/Login'));
const DemoLogin = React.lazy(() => import('./pages/DemoLogin'));
const OnboardingWizard = React.lazy(() => import('./pages/onboarding/OnboardingWizard'));
const Dashboard = React.lazy(() => import('./pages/Dashboard'));
const Invoices = React.lazy(() => import('./pages/Invoices'));
const Estimates = React.lazy(() => import('./pages/Estimates'));
const PdfTemplateStudio = React.lazy(() => import('./pages/PdfTemplateStudio'));
const LiveLinkTemplateStudio = React.lazy(() => import('./pages/LiveLinkTemplateStudio'));
const CreateInvoice = React.lazy(() => import('./pages/CreateInvoice'));
const HelpCenter = React.lazy(() => import('./pages/HelpCenter'));
const Customers = React.lazy(() => import('./pages/Customers'));
const Products = React.lazy(() => import('./pages/Products'));
const Settings = React.lazy(() => import('./pages/SettingsStudioV2'));
const Expenses = React.lazy(() => import('./pages/Expenses'));
const Subscription = React.lazy(() => import('./pages/Subscription'));
const MoreMenu = React.lazy(() => import('./pages/MoreMenu'));
const PublicInvoice = React.lazy(() => import('./pages/PublicInvoice'));
const PendingPayments = React.lazy(() => import('./pages/PendingPayments'));
const DueLedger = React.lazy(() => import('./pages/DueLedger'));
const TemplateMarketplace = React.lazy(() => import('./pages/TemplateMarketplace'));
const DesignStudio = React.lazy(() => import('./pages/DesignStudio'));
const BackupRestore = React.lazy(() => import('./pages/BackupRestore'));
const Reports = React.lazy(() => import('./pages/Reports'));
const PrivacyPolicy = React.lazy(() => import('./pages/PrivacyPolicy'));
const TermsOfService = React.lazy(() => import('./pages/TermsOfService'));
const RefundPolicy = React.lazy(() => import('./pages/RefundPolicy'));
const DataDeletion = React.lazy(() => import('./pages/DataDeletion'));
const Support = React.lazy(() => import('./pages/Support'));
const SystemHealth = React.lazy(() => import('./pages/SystemHealth'));
const AuditLogs = React.lazy(() => import('./pages/AuditLogs'));
const WorkspaceManager = React.lazy(() => import('./pages/WorkspaceManager'));
const Appointments = React.lazy(() => import('./pages/Appointments'));
const Orders = React.lazy(() => import('./pages/Orders'));
const Patients = React.lazy(() => import('./pages/business/Patients'));
const Students = React.lazy(() => import('./pages/business/Students'));
const Clients = React.lazy(() => import('./pages/business/Clients'));
const Measurements = React.lazy(() => import('./pages/business/Measurements'));
const DesignBook = React.lazy(() => import('./pages/business/DesignBook'));
const Devices = React.lazy(() => import('./pages/business/Devices'));
const ServiceJobs = React.lazy(() => import('./pages/business/ServiceJobs'));
const Projects = React.lazy(() => import('./pages/business/Projects'));
const Delivery = React.lazy(() => import('./pages/business/Delivery'));
const AdminPanel = React.lazy(() => import('./pages/admin/AdminPanel'));
const CyberDashboard = React.lazy(() => import('./pages/cybercafe/CyberDashboard'));
const PortalHub = React.lazy(() => import('./pages/cybercafe/PortalHub'));
const QuickToolsCenter = React.lazy(() => import('./pages/cybercafe/QuickToolsCenter'));
const CustomerRegister = React.lazy(() => import('./pages/cybercafe/CustomerRegister'));
const CashManagement = React.lazy(() => import('./pages/cybercafe/CashManagement'));
const PremiumPricing = React.lazy(() => import('./pages/PremiumPricing'));
const PaymentDueScreen = React.lazy(() => import('./pages/PaymentDueScreen'));
const SandboxAdmin = React.lazy(() => import('./pages/admin/SandboxAdmin'));
const StudentPortal = React.lazy(() => import('./pages/StudentPortal'));
const BillingPortal = React.lazy(() => import('./pages/BillingPortal'));

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null, errorInfo: null };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }

  componentDidCatch(error, errorInfo) {
    console.error("ErrorBoundary caught an error", error, errorInfo);
    
    // Automatically reload on Vite dynamic import failure (new deployment pushed)
    if (error && error.message && error.message.includes('Failed to fetch dynamically imported module')) {
      if (!sessionStorage.getItem('billqyro_chunk_failed_reload')) {
        sessionStorage.setItem('billqyro_chunk_failed_reload', 'true');
        window.location.reload();
        return;
      }
    }
    
    sendEmpireError({
      errorType: "app_crash",
      message: error?.toString() || "Unknown error",
      severity: "Critical",
      page: window.location.pathname
    });

    this.setState({ errorInfo });
  }

  render() {
    if (this.state.hasError) {
      return (
        <div style={{ padding: '20px', backgroundColor: '#fee2e2', color: '#991b1b', minHeight: '100vh', fontFamily: 'system-ui' }}>
          <h1 style={{ fontSize: '24px', fontWeight: 'bold' }}>Something went wrong.</h1>
          <p style={{ marginTop: '10px', fontWeight: 'bold' }}>Error: {this.state.error?.toString()}</p>
          <pre style={{ marginTop: '20px', padding: '10px', backgroundColor: '#fecaca', overflowX: 'auto', fontSize: '12px' }}>
            {this.state.errorInfo?.componentStack}
          </pre>
          <button onClick={() => window.location.reload()} style={{ marginTop: '20px', padding: '10px 20px', backgroundColor: '#dc2626', color: 'white', borderRadius: '5px', cursor: 'pointer' }}>
            Reload Page
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}



const AdminRouteGuard = ({ setCurrentTab, children }) => {
  const session = getAuthSession();
  const [isUnlocked, setIsUnlocked] = useState(
    localStorage.getItem('billqyro_admin_unlocked') === 'true'
  );

  useEffect(() => {
    // Only block access if the user is not an admin and hasn't unlocked the admin panel via PIN
    if (!isAdminUser(session) && !isUnlocked) {
      toast.error('Unauthorized access. Owner privileges required.');
      setCurrentTab('dashboard');
    }
  }, [session, setCurrentTab, isUnlocked]);

  // If not admin and not unlocked, show PIN login
  if (!isAdminUser(session) && !isUnlocked) {
    return (
      <AdminPINLogin
        onPinSuccess={() => setIsUnlocked(true)}
        onCancel={() => setCurrentTab('dashboard')}
      />
    );
  }

  return children;
};

function App() {

  // --- STATE SYSTEM (must be declared before any useEffect that references them) ---
  const [showWelcomeAnimation, setShowWelcomeAnimation] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const [showCommandPalette, setShowCommandPalette] = useState(false);

  useEffect(() => {
    const handleConfetti = () => {
      setShowConfetti(true);
      setTimeout(() => setShowConfetti(false), 5000);
    };
    const handleCommandPalette = () => {
      setShowCommandPalette(true);
    };
    window.addEventListener('trigger-confetti', handleConfetti);
    window.addEventListener('open-command-palette', handleCommandPalette);
    return () => {
      window.removeEventListener('trigger-confetti', handleConfetti);
      window.removeEventListener('open-command-palette', handleCommandPalette);
    };
  }, []);

  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    const realAuth = !!getAuthSession();
    const demoAuth = localStorage.getItem('billqyro_demo_session_active') === 'true' && 
                     localStorage.getItem('billqyro_demo_journey_mode') === 'true' && 
                     localStorage.getItem('billqyro_demo_logged_in') === 'true';
    return realAuth || demoAuth;
  });
  const [syncStatus, setSyncStatus] = useState('Synced');
  const [isDemoSessionActive, setIsDemoSessionActive] = useState(false);
  const [isVideoCreatorMode, setIsVideoCreatorMode] = useState(false);
  const [globalMaintenanceMode, setGlobalMaintenanceMode] = useState(false);
  
  const [demoInvoices, setDemoInvoices] = useState([]);
  const [demoCustomers, setDemoCustomers] = useState([]);
  const [demoProducts, setDemoProducts] = useState([]);
  const [demoExpenses, setDemoExpenses] = useState([]);
  const [demoSettings, setDemoSettings] = useState(null);

  useEffect(() => {
    const checkDemo = () => {
      const active = isDemoModeActive();
      setIsDemoSessionActive(active);
      const isVideo = localStorage.getItem('billqyro_demo_video_creator') === 'true';
      setIsVideoCreatorMode(isVideo);
      
      if (active) {
        autoGenerateDemoDataIfNeeded();
        setDemoInvoices(getDemoInvoices());
        setDemoCustomers(getDemoCustomers());
        setDemoProducts(getDemoProducts());
        
        // Reports / settings
        const s = JSON.parse(localStorage.getItem('billqyro_demo_settings') || 'null');
        setDemoSettings(s || {
           businessName: isVideo ? 'Demo Corp' : 'My Business (Demo)',
           ownerName: isVideo ? 'Demo Owner' : 'Me',
           email: isVideo ? 'hello@democorp.com' : 'demo@example.com',
           phone: isVideo ? '+1 555-0199' : '9999999999',
           themeColor: 'obsidian-gold'
        });
      }
    };
    checkDemo();
    window.addEventListener('storage', checkDemo);
    return () => window.removeEventListener('storage', checkDemo);
  }, []);

  const [currentTab, setCurrentTab] = useState(() => {
    if (window.location.pathname === '/km-admin') {
      return 'admin-panel';
    }
    const saved = localStorage.getItem('billqyro_last_route');
    const isAuth = !!getAuthSession() || (localStorage.getItem('billqyro_demo_session_active') === 'true' && localStorage.getItem('billqyro_demo_journey_mode') === 'true' && localStorage.getItem('billqyro_demo_logged_in') === 'true');
    if (isAuth && saved && saved !== 'admin-panel') {
      return saved;
    }
    if (!isAuth) return 'landing';
    return 'dashboard';
  });

  useEffect(() => {
    if (currentTab !== 'landing') {
      localStorage.setItem('billqyro_last_route', currentTab);
    }
    
    // Sync URL for km-admin to act like a real route
    if (currentTab === 'admin-panel') {
      window.history.replaceState({}, '', '/km-admin');
    } else if (window.location.pathname === '/km-admin') {
      window.history.replaceState({}, '', '/');
    }

    sendEmpireEvent({
      eventType: "page_view",
      message: `Navigated to ${currentTab}`,
      page: currentTab
    });
  }, [currentTab]);
  const [userRole, setUserRole] = useState(() => localStorage.getItem('billqyro_user_role') || 'user');

  // Capacitor Android Back Button Handler
  useEffect(() => {
    import('@capacitor/app').then(({ App: CapApp }) => {
      CapApp.removeAllListeners('backButton');
      CapApp.addListener('backButton', () => {
        setCurrentTab((prevTab) => {
          if (prevTab !== 'dashboard') {
            return 'dashboard';
          } else {
            CapApp.exitApp();
            return prevTab;
          }
        });
      });
    }).catch(() => { /* not in capacitor env */ });
  }, []);


  // Boot Interceptor for Public Invoice
  const [publicInvoice, setPublicInvoice] = useState(null);
  const [loadingPublicInvoice, setLoadingPublicInvoice] = useState(false);
  const [publicToken, setPublicToken] = useState(null);

  useEffect(() => {
    const path = window.location.pathname;
    const publicTokenMatch = path.match(/^\/invoice\/([a-zA-Z0-9_-]+)/);
    const urlParams = new URLSearchParams(window.location.search);
    const tokenFromQuery = urlParams.get('uuid') || urlParams.get('i');
    const token = (publicTokenMatch ? publicTokenMatch[1] : null) || tokenFromQuery;

    if (token) {
      setPublicToken(token);
      setLoadingPublicInvoice(true);
      import('./services/dbEngine').then(({ getInvoiceByPublicToken }) => {
        getInvoiceByPublicToken(token).then((inv) => {
          setPublicInvoice(inv);
          setLoadingPublicInvoice(false);
        });
      });
    }
  }, []);

  // Boot Interceptor for Portals
  const [portalId, setPortalId] = useState(null);
  const [eduPortalId, setEduPortalId] = useState(null);

  useEffect(() => {
    const path = window.location.pathname;
    
    // Strict redirect for Business workspaces trying to access student paths
    if (path === '/student' || path === '/students' || path.startsWith('/student/')) {
       const id = path.split('/')[2];
       if (id) {
         window.history.replaceState({}, '', `/billing/${id}`);
       } else {
         window.history.replaceState({}, '', '/billing');
       }
    }
    
    const newPath = window.location.pathname;

    const studentMatchLegacy = newPath.match(/^\/student\/([a-zA-Z0-9_-]+)/);
    const portalMatch = newPath.match(/^\/portal\/([a-zA-Z0-9_-]+)/);
    const billingMatch = newPath.match(/^\/billing\/([a-zA-Z0-9_-]+)/);
    const eduPortalMatch = newPath.match(/^\/student-portal\/([a-zA-Z0-9_-]+)/);
    
    if (eduPortalMatch) {
      setEduPortalId(eduPortalMatch[1]);
    } else if (portalMatch) {
      setPortalId(portalMatch[1]);
    } else if (billingMatch) {
      setPortalId(billingMatch[1]);
    } else if (studentMatchLegacy) {
      setPortalId(studentMatchLegacy[1]);
    }
  }, []);

  // Storage states
  const [invoices, setInvoices] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [products, setProducts] = useState([]);
  // Settings with workspace support
  const [settings, setSettings] = useState(() => {
    const s = getSettings() || {};
    if (!s.businessWorkspaces) {
      // Initialize default workspace
      const defaultWs = {
        id: 'ws_default_001',
        name: 'Default Workspace',
        type: 'default',
        enabledModules: ['billing', 'customers', 'products', 'dueLedger', 'reports'],
      };
      s.businessWorkspaces = [defaultWs];
      s.activeWorkspaceId = defaultWs.id;
    } else if (!s.activeWorkspaceId && s.businessWorkspaces.length) {
      s.activeWorkspaceId = s.businessWorkspaces[0].id;
    }
    // Persist defaults if newly added
    saveSettings(s);
    return s;
  });
  const [expenses, setExpenses] = useState([]);
  const [subscription, setSubscription] = useState(() => getSubscriptionStatus());
  const [revenueStatus, setRevenueStatus] = useState({
    totalBillsCreated: 0,
    freeBillsUsed: 0,
    billableBillsCount: 0,
    platformDueAmount: 0,
    platformPaidAmount: 0,
    platformPendingAmount: 0,
    lastPlatformPaymentDate: null,
    lockStatus: 'none',
    graceStatus: 'none',
    premiumStatus: 'free'
  });

  useEffect(() => {
    const fetchRevenue = async () => {
      const session = getAuthSession();
      const userId = session?.uid || getRealUserId() || 'local-user';
      try {
        const status = await getUserRevenueState(userId, invoices, subscription);
        setRevenueStatus(status);
      } catch (e) {
        console.error('Failed to load user revenue status:', e);
      }
    };
    fetchRevenue();
  }, [invoices, subscription, isAuthenticated]);
  // Workspace state
  const [businessWorkspaces, setBusinessWorkspaces] = useState(settings.businessWorkspaces || []);
  const [activeWorkspaceId, setActiveWorkspaceId] = useState(settings.activeWorkspaceId || (settings.businessWorkspaces && settings.businessWorkspaces[0]?.id));

  // Keep workspaces in sync with cloud settings updates
  useEffect(() => {
    if (settings.businessWorkspaces && JSON.stringify(settings.businessWorkspaces) !== JSON.stringify(businessWorkspaces)) {
      setBusinessWorkspaces(settings.businessWorkspaces);
    }
    if (settings.activeWorkspaceId && settings.activeWorkspaceId !== activeWorkspaceId) {
      setActiveWorkspaceId(settings.activeWorkspaceId);
    }
  }, [settings]);

  // Handle local workspace changes
  const updateWorkspaceState = (newWorkspaces, newActiveId) => {
    setBusinessWorkspaces(newWorkspaces);
    setActiveWorkspaceId(newActiveId);
    setSettings(prev => {
      const updated = { ...prev, businessWorkspaces: newWorkspaces, activeWorkspaceId: newActiveId };
      saveSettings(updated);
      window.dispatchEvent(new CustomEvent('billqyro_sync'));
      return updated;
    });
  };

  const setActiveWorkspace = (id) => {
    updateWorkspaceState(businessWorkspaces, id);
  };

  // Real-time Pending Payments state
  const [pendingPayments, setPendingPayments] = useState([]);
  
  useEffect(() => {
    if (!isAuthenticated || !db || !auth) return;
    
    let unsubscribe = () => {};
    
    // Listen for auth state changes to get current user UID
    const authUnsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        const q = query(
          collection(db, 'payment_proofs'),
          where('ownerId', '==', user.uid),
          where('status', '==', 'pending')
        );
        
        unsubscribe = onSnapshot(q, (snapshot) => {
          const proofs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
          setPendingPayments(proofs);
        });
      } else {
        setPendingPayments([]);
      }
    });
    
    return () => {
      authUnsubscribe();
      unsubscribe();
    };
  }, [isAuthenticated]);
  
  // --- 🚀 GLOBAL BOOT & LOADING STATE ---
  const [isAppBooting, setIsAppBooting] = useState(true);
  const [isDataHydrating, setIsDataHydrating] = useState(true);
  const [cloudSyncDone, setCloudSyncDone] = useState(false);

  // Safety timeout to ensure app never gets stuck on boot screen
  useEffect(() => {
    if (isAppBooting) {
      const timeout = setTimeout(() => {
        console.warn('[BOOT TIMEOUT] 3000ms reached, forcing app load.');
        setIsAppBooting(false);
      }, 3000);
      return () => clearTimeout(timeout);
    }
  }, [isAppBooting]);

  // Async Data Loader & Boot Sequence
  useEffect(() => {
    let isBooted = false;

    const loadLocalData = async () => {
      sendEmpireEvent({ eventType: "app_opened", message: "BillQyro Web App Opened", page: "init" });
      sendEmpireHealth({ status: "Healthy", healthScore: 100, note: "App initialized successfully" });
      
      try {
        setInvoices(await getInvoices() || []);
        setCustomers(await getCustomers() || []);
        setProducts(await getProducts() || []);
        setExpenses(await getExpenses() || []);
      } catch (err) {
        console.error("Error loading local data:", err);
      } finally {
        setIsDataHydrating(false);
        isBooted = true;
        setIsAppBooting(false);
      }
    };
    loadLocalData();

    const handleSync = async () => {
      if (!isBooted) return;
      try {
        setInvoices(await getInvoices() || []);
        setCustomers(await getCustomers() || []);
        setProducts(await getProducts() || []);
        setExpenses(await getExpenses() || []);
        const latestSettings = getSettings();
        if (latestSettings) {
          if (isAdminUser(getAuthSession()) && latestSettings.maintenanceMode) {
            const cleaned = { ...latestSettings };
            delete cleaned.maintenanceMode;
            setSettings(cleaned);
            saveSettings(cleaned);
          } else {
            setSettings(latestSettings);
          }
        }
        setSubscription(getSubscriptionStatus());
      } catch (err) {
        console.error("Error reloading data on sync:", err);
      }
    };
    window.addEventListener('billqyro_sync', handleSync);
    
    // --- Pro Sync Engine Event Bus ---
    const handleSettingsUpdated = (e) => {
      if (e.detail) setSettings(e.detail);
    };
    const handleDataUpdated = async (e) => {
      const col = e.detail?.collectionName;
      if (col === 'invoices') setInvoices(await getInvoices() || []);
      if (col === 'customers') setCustomers(await getCustomers() || []);
      if (col === 'products') setProducts(await getProducts() || []);
    };
    const handleSyncStatus = (e) => {
      if (e.detail) setSyncStatus(e.detail);
    };
    window.addEventListener('billqyro:settings-updated', handleSettingsUpdated);
    window.addEventListener('billqyro:data-updated', handleDataUpdated);
    window.addEventListener('billqyro:sync-status', handleSyncStatus);
    
    const handleNavigate = (e) => {
      if (e.detail) {
        setCurrentTab(e.detail);
      }
    };
    window.addEventListener('navigate_tab', handleNavigate);

    return () => {
      window.removeEventListener('billqyro_sync', handleSync);
      window.removeEventListener('billqyro:settings-updated', handleSettingsUpdated);
      window.removeEventListener('billqyro:data-updated', handleDataUpdated);
      window.removeEventListener('billqyro:sync-status', handleSyncStatus);
      window.removeEventListener('navigate_tab', handleNavigate);
    };
  }, []);

  // Workspace Contexts
  const [editingInvoice, setEditingInvoice] = useState(null);
  const [showPaywallModal, setShowPaywallModal] = useState(false);

  // PWA Installer States
  const [installPromptEvent, setInstallPromptEvent] = useState(null);
  const [isAppInstalled, setIsAppInstalled] = useState(false);
  const [isQuickBillOpen, setIsQuickBillOpen] = useState(false);

  // Initialize Smart SVG Dynamic Theme Engine
  useThemeEngine(settings);

  useEffect(() => {
    const handleBeforeInstallPrompt = (e) => {
      e.preventDefault();
      setInstallPromptEvent(e);
      // PWA install prompt stashed
    };

    const handleAppInstalled = () => {
      setInstallPromptEvent(null);
      setIsAppInstalled(true);
      toast.success('🎉 BillQyro App installed successfully!');
    };

    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
    window.addEventListener('appinstalled', handleAppInstalled);

    if (window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true) {
      setIsAppInstalled(true);
    }

    return () => {
      window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
      window.removeEventListener('appinstalled', handleAppInstalled);
    };
  }, []);

  const handleInstallApp = async () => {
    if (!installPromptEvent) return;
    installPromptEvent.prompt();
    const { outcome } = await installPromptEvent.userChoice;
    // User install choice handled
    setInstallPromptEvent(null);
  };

  // --- EFFECTS ---

  // Initialize Database on App mount
  useEffect(() => {
    initializeStorage();
  }, []);

  // Listen to Firebase Auth state
  useEffect(() => {
    if (firebaseReady && auth) {
      const unsubscribe = onAuthStateChanged(auth, (user) => {
        // Firebase auth state updated
        if (user) {
          const session = getAuthSession();
          const newSession = {
            timestamp: Date.now(),
            token: 'billqyro-secure-session',
            userEmail: user.email || '',
            uid: user.uid
          };
          localStorage.setItem('billqyro_auth', JSON.stringify(newSession));
          setIsAuthenticated(true);
          setUserRole(localStorage.getItem('billqyro_user_role') || 'user');
        } else {
          setIsAuthenticated(false);
          setIsAppBooting(false); // Force exit loading state if no real user exists
          setIsDataHydrating(false);
        }
      });
      return () => unsubscribe();
    } else {
      setIsAppBooting(false);
      setIsDataHydrating(false);
    }
  }, []);

  // Sync from Firebase Firestore when authenticated
  useEffect(() => {
    if (isAuthenticated) {
      const runSync = async () => {
        try {
          const synced = await syncFromFirestore();
          if (synced) {
            if (synced.invoices) setInvoices(synced.invoices);
            if (synced.customers) setCustomers(synced.customers);
            if (synced.products) setProducts(synced.products);
            if (synced.settings) setSettings(synced.settings);
            if (synced.expenses) setExpenses(synced.expenses);
            if (synced.subscription) setSubscription(synced.subscription);
          }
          
          // Fetch global admin settings for defaults
          try {
            const adminGlobal = await getGlobalAdminSettings();
            if (adminGlobal) {
              if (adminGlobal.defaultTheme) {
                localStorage.setItem('billqyro_admin_default_theme', adminGlobal.defaultTheme);
                if (!synced?.settings?.themeColor && !synced?.settings?.brandColor) {
                  // Handled by ThemeContext
                  import('./utils/themeIcon').then(m => m.updateFaviconForTheme(adminGlobal.defaultTheme));
                }
              }
              if (adminGlobal.defaultMode) {
                localStorage.setItem('billqyro_admin_default_mode', adminGlobal.defaultMode);
                if (!synced?.settings?.displayMode) {
                  // Handled by ThemeContext
                }
              }
            }
          } catch (e) { console.warn('Could not fetch admin settings on boot.'); }

          try {
            const ann = await getActiveAnnouncement();
            if (ann && ann.type === 'maintenance') {
              setGlobalMaintenanceMode(true);
            } else {
              setGlobalMaintenanceMode(false);
            }
          } catch (e) { console.warn('Could not fetch active announcement on boot.'); }

          // Enable real-time multi-device sync via new Sync Engine
          import('./services/syncEngine').then(({ startRealTimeSync }) => {
            const userId = auth.currentUser?.uid;
            if (userId) {
              startRealTimeSync(userId, (newSettings) => {
                setSettings(newSettings);
              });
            }
          });
        } catch (e) {
          sendEmpireError({ errorType: "sync_failed", message: "Could not sync Firestore on startup", severity: "Medium" });
          console.warn('Could not sync Firestore on startup. Falling back to LocalStorage.', e);
        } finally {
          setIsAppBooting(false); // ALWAYS EXIT BOOT
          setCloudSyncDone(true);
        }
      };
      runSync();
    }
  }, [isAuthenticated]);



  // --- AUTH BRIDGE ---
  const handleLoginSuccess = () => {
    if (!sessionStorage.getItem('billqyro_welcome_shown')) {
      setShowWelcomeAnimation(true);
      sessionStorage.setItem('billqyro_welcome_shown', 'true');
    }
    // Auth state changes (isAuthenticated, sync) are handled reactively by onAuthStateChanged.
  };

  // Onboarding Interceptor for Authenticated Session Boot
  useEffect(() => {
    // Wait until boot and sync is completely finished
    if (isAuthenticated && !isAppBooting && settings && cloudSyncDone) {
      // Onboarding check complete
      const isLegacyConfigured = !!(settings.businessName && settings.businessName.trim());
      
      if (!settings.setupCompleted && !isLegacyConfigured) {
        if (currentTab !== 'onboarding') {
          setCurrentTab('onboarding');
        }
      } else if (!settings.setupCompleted && isLegacyConfigured) {
        // Silently upgrade legacy users to completed setup
        const updated = { ...settings, setupCompleted: true };
        saveSettings(updated);
        setSettings(updated);
        if (currentTab === 'onboarding') {
          setCurrentTab('dashboard');
        }
      } else if (settings.setupCompleted) {
        if (currentTab === 'onboarding') {
          setCurrentTab('dashboard');
        }
      }
    }
  }, [isAuthenticated, isAppBooting, settings, currentTab]);

  const handleLogout = async () => {
    try {
      if (firebaseReady && auth) {
        await auth.signOut();
      }
    } catch (err) {
      console.error('Firebase sign out error', err);
    }
    logout();
    localStorage.removeItem('billqyro_user_role');
    localStorage.removeItem('billqyro_admin_unlocked');
    setUserRole('user');
    setIsAuthenticated(false);
    setCurrentTab('dashboard');
  };

  // --- DATA SYNCHRONIZERS ---

  // Invoices
  const handleSaveInvoice = async (payload, saveCustomerAsNew = false, isSilent = false) => {
    if (isDemoSessionActive) {
      if (!payload.id) {
        payload.id = 'demo-inv-' + Date.now();
        if (!payload.invoiceNumber) payload.invoiceNumber = 'DEMO-INV-' + (1000 + demoInvoices.length);
      }
      saveDemoInvoice(payload);
      if (!isSilent) {
        toast.success('Saved to Demo Session');
        setEditingInvoice(null);
        setCurrentTab('dashboard'); // Redirect to dashboard to see real-time updates!
      }
      return;
    }

    // Flatten nested InvoiceContext state if present
    if (payload.customer && typeof payload.customer === 'object') {
      payload.customerId = payload.customer.id || payload.customerId;
      payload.customerName = payload.customer.name || payload.customerName;
      payload.customerPhone = payload.customer.phone || payload.customerPhone;
      payload.customerEmail = payload.customer.email || payload.customerEmail;
      payload.customerAddress = payload.customer.address || payload.customerAddress;
      delete payload.customer;
    }
    if (payload.totals && typeof payload.totals === 'object') {
      payload.subtotal = payload.totals.subtotal || payload.subtotal || 0;
      payload.taxPercentage = payload.totals.taxPercentage ?? payload.taxPercentage ?? 18;
      payload.taxAmount = payload.totals.taxAmount || payload.taxAmount || 0;
      payload.discountAmount = payload.totals.discountAmount || payload.discountAmount || 0;
      payload.grandTotal = payload.totals.grandTotal || payload.grandTotal || 0;
      payload.amountPaid = payload.totals.amountPaid || payload.amountPaid || 0;
      payload.balanceDue = payload.totals.balanceDue || payload.balanceDue || 0;
      delete payload.totals;
    }
    if (payload.settings && typeof payload.settings === 'object') {
      payload.notes = payload.settings.notes || payload.notes || '';
      payload.terms = payload.settings.terms || payload.terms || '';
      payload.paymentStatus = payload.settings.paymentStatus || payload.paymentStatus || 'Unpaid';
      payload.orderStatus = payload.settings.orderStatus || payload.orderStatus || 'Pending';
      payload.paymentMethod = payload.settings.paymentMethod || payload.paymentMethod || 'Cash';
      payload.paymentNote = payload.settings.paymentNote || payload.paymentNote || '';
      if (payload.settings.auditHistory) {
        payload.auditHistory = payload.settings.auditHistory;
      }
      delete payload.settings;
    }

    // Advanced Payload Validation
    const validationResult = validatePayload(invoiceSchema, payload);
    if (!validationResult.success && !isDemoSessionActive) {
      toast.error('Validation Error: Invalid invoice data.');
      console.error('Invoice Validation Failed:', validationResult.errors);
      return;
    }
    const validatedPayload = validationResult.success ? validationResult.data : payload;

    // Final Integrity Check
    if (payload.items && payload.items.length > 0) {
      const hasValidItems = payload.items.some(i => (parseFloat(i.qty) || 0) > 0 && (parseFloat(i.rate) || 0) > 0);
      if (hasValidItems && (!payload.grandTotal || payload.grandTotal === 0)) {
        console.warn('⚠️ CRITICAL: Attempted to save invoice with ₹0 grand total but valid items exist. Forcing recalculation to prevent data corruption.');
        const recalculated = calculateTotals(payload.items, payload.taxPercentage || 0, payload.discountAmount || 0);
        payload.subtotal = recalculated.subtotal;
        payload.taxAmount = recalculated.taxAmount;
        payload.grandTotal = recalculated.grandTotal;
        payload.balanceDue = Math.max(0, recalculated.grandTotal - (payload.amountPaid || 0));
      }
    }

    const isNew = !payload.id || !invoices.some(inv => inv.id === payload.id);
    if (isNew && revenueStatus.lockStatus === 'locked') {
      toast.error('New invoice creation is locked. Please clear your platform dues.');
      return;
    }
    const freeLimit = settings?.freeInvoiceLimit !== undefined ? settings.freeInvoiceLimit : 15;
    const isPPBActive = revenueStatus.lockStatus !== 'none' || revenueStatus.platformDueAmount > 0;
    if (isNew && subscription.status !== 'premium' && invoices.length >= freeLimit && !isSilent && !isPPBActive) {
      setShowPaywallModal(true);
      return;
    }
    let unlinkedItems = false;
    let lowStockWarning = false;

    let productsUpdated = false;
    const currentProducts = [...products];
    const updatedProductIds = new Set();

    // 1. If editing an existing invoice, reverse previous stock deduction
    const oldInvoice = payload.id ? invoices.find(inv => inv.id === payload.id) : null;
    if (oldInvoice && oldInvoice.items) {
      for (const oldItem of oldInvoice.items) {
        const itemName = (oldItem.description || oldItem.productName || oldItem.serviceName || oldItem.itemService || '').trim().toLowerCase();
        if (!itemName) continue;

        const matchedProduct = currentProducts.find(p => p.name.trim().toLowerCase() === itemName);
        if (matchedProduct && matchedProduct.stockQty !== undefined) {
          const oldQty = parseFloat(oldItem.qty) || 1;
          matchedProduct.stockQty += oldQty;
          updatedProductIds.add(matchedProduct.id);
          productsUpdated = true;
        }
      }
    }

    // 2. Apply new stock deduction
    for (const item of payload.items) {
      const itemName = (item.description || item.productName || item.serviceName || item.itemService || '').trim().toLowerCase();
      if (!itemName) continue;

      const matchedProduct = currentProducts.find(p => p.name.trim().toLowerCase() === itemName);
      
      if (matchedProduct) {
        const requestedQty = parseFloat(item.qty) || 1;
        const currentStock = matchedProduct.stockQty !== undefined ? matchedProduct.stockQty : 0;
        if (currentStock < requestedQty) {
          lowStockWarning = true;
          matchedProduct.stockQty = 0; // Prevent going below 0 without confirmation
        } else {
          matchedProduct.stockQty = currentStock - requestedQty;
        }
        updatedProductIds.add(matchedProduct.id);
        productsUpdated = true;
      } else {
        unlinkedItems = true;
      }
    }

    if (productsUpdated) {
      const savePromises = [];
      for (const p of currentProducts) {
        if (updatedProductIds.has(p.id)) {
          savePromises.push(saveProduct(p));
        }
      }
      Promise.all(savePromises).catch(e => console.error("Error saving products:", e));
      setProducts(currentProducts);
    }

    // Fire and forget saveInvoice for Layer 2 persistence
    saveInvoice(payload).then(({ updatedInvoices, firebaseStatus }) => {
      setInvoices(updatedInvoices);

      if (!isSilent) {
        if (firebaseStatus === 'failed') {
          toast.success('Invoice created successfully. (Saved locally. Firebase sync pending.)');
        } else {
          toast.success('Invoice created successfully');
        }
        
        sendEmpireEvent({
          eventType: "invoice_created",
          message: "Invoice created in BillQyro",
          page: "create-invoice",
          metadata: { feature: "invoice", action: "created", privateDataIncluded: false }
        });

        // Trigger haptic & audio feedback
        triggerSuccessFeedback();

        if (unlinkedItems) {
          toast.custom(
            (t) => (
              <div className={`${t.visible ? 'animate-enter' : 'animate-leave'} max-w-md w-full bg-theme-warning/5 dark:bg-amber-950/40 shadow-lg rounded-xl pointer-events-auto flex ring-1 ring-amber-500/30`}>
                <div className="flex-1 w-0 p-4">
                  <div className="flex items-start">
                    <div className="flex-shrink-0 pt-0.5">
                      <span className="text-xl">⚠️</span>
                    </div>
                    <div className="ml-3 flex-1">
                      <p className="text-sm font-semibold text-amber-800 dark:text-amber-300">
                        Some bill items are not linked to products, so inventory stock was not updated.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="flex border-l border-amber-500/20">
                  <button
                    onClick={() => {
                      toast.dismiss(t.id);
                      setCurrentTab('products');
                    }}
                    className="w-full border border-transparent rounded-none rounded-r-xl p-4 flex items-center justify-center text-xs font-bold text-amber-700 dark:text-amber-400 hover:bg-theme-warning/10 focus:outline-none transition-colors"
                  >
                    Link Products
                  </button>
                </div>
              </div>
            ),
            { duration: 6000 }
          );
        } else if (productsUpdated) {
          toast.success('Inventory stock updated successfully.', { duration: 4000 });
        }

        if (lowStockWarning) {
          toast.error('Low stock or insufficient stock for some products.', { duration: 4000 });
        }

        setEditingInvoice(null);
        setCurrentTab('invoices');
      }
    }).catch(e => console.error("Error saving invoice locally:", e));

    if (saveCustomerAsNew && payload.customerName && !isSilent) {
      const newCustomer = {
        id: 'cust-' + Date.now(),
        name: payload.customerName,
        phone: payload.customerPhone || '',
        email: payload.customerEmail || '',
        address: payload.customerAddress || ''
      };
      saveCustomer(newCustomer).then(({ updatedCustomers }) => {
        setCustomers(updatedCustomers);
      }).catch(e => console.error("Error saving customer:", e));
    }

    return payload;
  };

  const handleDeleteInvoice = async (id, permanent = false) => {
    if (isDemoSessionActive) {
      deleteDemoInvoice(id);
      toast.success('Deleted from Demo Session');
      return;
    }

    const executeDelete = async () => {
      const { updatedInvoices, firebaseStatus } = await deleteInvoice(id, permanent);
      setInvoices(updatedInvoices);
      if (firebaseStatus === 'failed') {
        toast.success(permanent ? 'Invoice permanently deleted locally. Will sync when online.' : 'Invoice moved to trash locally.');
      } else {
        toast.success(permanent ? 'Invoice permanently deleted!' : 'Invoice moved to trash.');
      }
    };

    if (permanent) {
      await executeDelete();
    } else {
      toast.custom(
        (t) => (
          <div className={`${t.visible ? 'animate-enter' : 'animate-leave'} max-w-sm w-full bg-theme-app dark:bg-theme-surface shadow-2xl rounded-2xl pointer-events-auto border border-theme-border-soft overflow-hidden`}>
            <div className="p-5 flex flex-col items-center text-center">
              <div className="w-12 h-12 rounded-full bg-theme-danger/10 text-theme-danger flex items-center justify-center mb-3">
                <Trash2 className="w-6 h-6" />
              </div>
              <h3 className="text-lg font-black text-theme-primary dark:text-theme-primary mb-1">Move to Trash?</h3>
              <p className="text-xs text-theme-muted font-semibold mb-6">
                Are you sure you want to move this invoice to the trash? You can restore it later if needed.
              </p>
              <div className="flex w-full gap-2">
                <button
                  onClick={() => toast.dismiss(t.id)}
                  className="flex-1 bg-theme-card border border-theme-border-soft text-theme-muted font-bold py-2.5 rounded-xl transition-all hover:bg-theme-border-soft"
                >
                  Cancel
                </button>
                <button
                  onClick={async () => {
                    toast.dismiss(t.id);
                    await executeDelete();
                  }}
                  className="flex-1 bg-theme-danger text-white font-bold py-2.5 rounded-xl transition-all hover:bg-rose-600 shadow-md"
                >
                  Yes, Delete
                </button>
              </div>
            </div>
          </div>
        ),
        { duration: 5000 }
      );
    }
  };

  // Customers
  const handleSaveCustomer = async (payload) => {
    // Validate Customer Payload
    const validationResult = validatePayload(customerSchema, payload);
    if (!validationResult.success) {
      toast.error('Validation Error: Invalid customer data.');
      console.error('Customer Validation Failed:', validationResult.errors);
      return;
    }
    const validatedCust = validationResult.data;

    if (isDemoSessionActive) {
      if (!validatedCust.id) {
        validatedCust.id = 'demo-cust-' + Date.now();
      }
      saveDemoCustomer(validatedCust);
      toast.success('Saved to Demo Session');
      return;
    }
    try {
      const { updatedCustomers, firebaseStatus } = await saveCustomer(validatedCust);
      setCustomers(updatedCustomers);
      if (firebaseStatus === 'failed') {
        toast.success('Customer saved locally. Will sync with cloud when online.');
      } else {
        toast.success('Customer saved successfully');
      }
      sendEmpireEvent({
        eventType: "customer_added",
        message: "Customer saved",
        page: "customers",
        metadata: { feature: "customer", action: "added", privateDataIncluded: false }
      });
    } catch (error) {
      console.error(error);
      toast.error('Failed to save customer');
    }
  };

  const handleDeleteCustomer = async (id) => {
    if (isDemoSessionActive) {
      const customers = getDemoCustomers().filter(i => i.id !== id);
      localStorage.setItem('billqyro_demo_customers', JSON.stringify(customers));
      toast.success('Deleted from Demo Session');
      window.dispatchEvent(new Event('storage'));
      return;
    }
    if (window.confirm('Are you sure you want to delete this customer?')) {
      const { updatedCustomers, firebaseStatus } = await deleteCustomer(id);
      setCustomers(updatedCustomers);
      if (firebaseStatus === 'failed') {
        toast.success('Customer deleted locally. Will sync with cloud when online.');
      } else {
        toast.success('Customer deleted');
      }
    }
  };

  // Products
  const handleSaveProduct = async (payload) => {
    if (isDemoSessionActive) {
      if (!payload.id) {
        payload.id = 'demo-prod-' + Date.now();
      }
      saveDemoProduct(payload);
      toast.success('Saved to Demo Session');
      return;
    }
    try {
      const { updatedProducts, firebaseStatus } = await saveProduct(payload);
      setProducts(updatedProducts);
      if (firebaseStatus === 'failed') {
        toast.success('Product/Service saved locally. Will sync with cloud when online.');
      } else {
        toast.success('Product/Service saved successfully');
      }
      sendEmpireEvent({
        eventType: "product_added",
        message: "Product saved",
        page: "products",
        metadata: { feature: "product", action: "added", privateDataIncluded: false }
      });
    } catch (error) {
      console.error(error);
      toast.error('Failed to save product');
    }
  };

  const handleDeleteProduct = async (id) => {
    if (isDemoSessionActive) {
      const products = getDemoProducts().filter(i => i.id !== id);
      localStorage.setItem('billqyro_demo_products', JSON.stringify(products));
      toast.success('Deleted from Demo Session');
      window.dispatchEvent(new Event('storage'));
      return;
    }
    const { updatedProducts, firebaseStatus } = await deleteProduct(id);
    setProducts(updatedProducts);
    if (firebaseStatus === 'failed') {
      toast.success('Product deleted locally. Will sync with cloud when online.', { id: 'delete-product-toast' });
    }
  };

  // Expenses
  const handleSaveExpense = async (payload) => {
    try {
      const { updatedExpenses, firebaseStatus } = await saveExpense(payload);
      setExpenses(updatedExpenses);
      if (firebaseStatus === 'failed') {
        toast.success('Expense saved locally. Will sync with cloud when online.');
      } else {
        toast.success('Expense saved successfully');
      }
    } catch (error) {
      console.error(error);
      toast.error('Failed to save expense');
    }
  };

  const handleDeleteExpense = async (id) => {
    const { updatedExpenses, firebaseStatus } = await deleteExpense(id);
    setExpenses(updatedExpenses);
    if (firebaseStatus === 'failed') {
      toast.success('Expense deleted locally. Will sync with cloud when online.', { id: 'delete-expense-toast' });
    }
  };

  // Subscription
  const handleSaveSubscription = (status) => {
    const updated = saveSubscriptionStatus(status);
    setSubscription(updated);
  };

  // Settings
  const handleSaveSettings = async (payload) => {
    if (isDemoSessionActive) {
      localStorage.setItem('billqyro_demo_settings', JSON.stringify(payload));
      toast.success('Settings saved to Demo Session');
      window.dispatchEvent(new Event('storage'));
      return;
    }
    try {
      const updatedSettings = await saveSettings(payload);
      setSettings(updatedSettings);
      toast.success('Settings saved successfully');
      sendEmpireEvent({
        eventType: "settings_updated",
        message: "App settings updated",
        page: "settings",
        metadata: { privateDataIncluded: false }
      });
    } catch (error) {
      console.error(error);
      toast.error('Failed to save settings');
    }
  };

  // Reset System Data
  const handleResetDemo = () => {
    const freshData = resetToDemoData();
    setSettings(freshData.settings);
    setCustomers(freshData.customers);
    setProducts(freshData.products);
    setInvoices(freshData.invoices);
    setExpenses(freshData.expenses);
    setSubscription(freshData.subscription);
    toast.success('Demo data has been reset!');
    setCurrentTab('dashboard');
  };

  // Import Backup Data and Sync React States
  const handleImportBackup = (parsedData) => {
    importRestore(parsedData);
    setSettings(parsedData.settings);
    setCustomers(parsedData.customers);
    setProducts(parsedData.products);
    setInvoices(parsedData.invoices);
    setExpenses(parsedData.expenses);
    setSubscription(parsedData.subscription);
    setCurrentTab('dashboard');
  };

  // --- PDF GENERATOR WORKER ---
  const handleDownloadPDF = (invoice) => {
    if (!settings || !settings.businessName) {
      alert('⚠️ Business settings are incomplete. Please complete your business settings first.');
      setCurrentTab('settings');
      return;
    }
    const isPremium = subscription.status === 'premium';
    downloadInvoicePDF(invoice, settings, isPremium)
      .then((ok) => {
        if (ok) {
          sendEmpireEvent({
            eventType: "pdf_downloaded",
            message: "Invoice PDF generated",
            page: "invoice",
            metadata: { feature: "pdf", action: "downloaded", privateDataIncluded: false }
          });
        }
      })
      .catch((err) => {
        sendEmpireError({
          errorType: "pdf_failed",
          message: err?.toString() || "PDF generation failed",
          severity: "Medium",
          page: "invoice"
        });
      });
  };

  // HARD DEMO MODE ISOLATION SWITCH
  const activeInvoices = isDemoSessionActive ? demoInvoices : invoices;
  const activeCustomers = isDemoSessionActive ? demoCustomers : customers;
  const activeProducts = isDemoSessionActive ? demoProducts : products;
  const activeExpenses = isDemoSessionActive ? demoExpenses : expenses;
  
  let activeSettings = (isDemoSessionActive && demoSettings) ? demoSettings : settings;
  if (isDemoSessionActive && isVideoCreatorMode && activeSettings) {
    activeSettings = {
      ...activeSettings,
      businessName: activeSettings.businessName || 'Demo Corp',
      ownerName: 'Demo Owner',
      email: 'hello@democorp.local',
      phone: '+1 555-0199',
      logoUrl: '',
      whatsapp: '+1 555-0199'
    };
  }

  // --- TAB ROUTER SWITCHBOARD ---
  const renderTabContent = () => {
    const isMaintenanceMode = (globalMaintenanceMode || activeSettings?.maintenanceMode) && !isAdminUser(getAuthSession());

    switch (currentTab) {
      case 'landing':
        return <Landing onLoginSuccess={handleLoginSuccess} />;
      case 'cyber-dashboard':
        return <CyberDashboard setCurrentTab={setCurrentTab} />;
      case 'portal-hub':
        return <PortalHub />;
      case 'quick-tools':
        return <QuickToolsCenter />;
      case 'customer-register':
        return <CustomerRegister />;
      case 'cash-management':
        return <CashManagement />;
      case 'dashboard':
        return (
          <Dashboard
            invoices={activeInvoices}
            customers={activeCustomers}
            products={activeProducts}
            expenses={activeExpenses}
            onViewInvoice={(inv) => {
              setEditingInvoice(inv);
              setCurrentTab('invoices');
            }}
            onEditInvoice={(inv) => {
              setEditingInvoice(inv);
              setCurrentTab('create-invoice');
            }}
            onDeleteInvoice={handleDeleteInvoice}
            onDownloadPDF={handleDownloadPDF}
            setCurrentTab={setCurrentTab}
            businessSettings={activeSettings}
            installPromptEvent={installPromptEvent}
            isAppInstalled={isAppInstalled}
            onInstallApp={handleInstallApp}
            subscription={subscription}
            onQuickBillOpen={() => setIsQuickBillOpen(true)}
            pendingPaymentsCount={pendingPayments.length}
            isLoading={isDataHydrating}
            revenueStatus={revenueStatus}
            onSaveCustomer={handleSaveCustomer}
          />
        );
      case 'pending-payments':
        return (
          <PendingPayments 
            setCurrentTab={setCurrentTab}
            pendingPayments={pendingPayments}
          />
        );
      case 'help-center':
        return (
          <HelpCenter />
        );
      case 'system-health':
        return <SystemHealth setCurrentTab={setCurrentTab} />;
      case 'sandbox-admin':
        return <SandboxAdmin setCurrentTab={setCurrentTab} />;
      case 'audit-logs':
        return (
          <AuditLogs setCurrentTab={setCurrentTab} />
        );
      case 'due':
      case 'due-ledger':
        return (
          <DueLedger 
            customers={activeCustomers} 
            invoices={activeInvoices} 
            businessSettings={activeSettings}
          />
        );
      case 'reports':
        return (
          <Reports 
            invoices={activeInvoices} 
            customers={activeCustomers} 
            businessSettings={activeSettings}
          />
        );
      case 'invoices':
        return (
          <Invoices
            invoices={activeInvoices}
            editingInvoice={editingInvoice}
            onEditInvoice={setEditingInvoice}
            onDeleteInvoice={handleDeleteInvoice}
            onDownloadPDF={handleDownloadPDF}
            setCurrentTab={setCurrentTab}
            businessSettings={activeSettings}
          />
        );
      case 'estimates':
        return (
          <Estimates
            invoices={activeInvoices}
            editingInvoice={editingInvoice}
            onEditInvoice={setEditingInvoice}
            onDeleteInvoice={handleDeleteInvoice}
            onDownloadPDF={handleDownloadPDF}
            setCurrentTab={setCurrentTab}
            businessSettings={activeSettings}
            onSaveInvoice={handleSaveInvoice}
          />
        );
      case 'create-invoice':
        if ((isMaintenanceMode || activeSettings?.disableNewBillCreation) && !editingInvoice) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">New Bill Creation Disabled</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                The platform is currently undergoing scheduled maintenance or the owner has disabled new bill creation. You can still view existing bills and run backups.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Go to Dashboard
              </button>
            </div>
          );
        }
        if (revenueStatus.lockStatus === 'locked' && !editingInvoice) {
          return (
            <React.Suspense fallback={<div className="flex h-screen items-center justify-center"><ClassicLoader /></div>}>
              <PaymentDueScreen 
                pendingAmount={revenueStatus.platformPendingAmount}
                chargeableBills={revenueStatus.billableBillsCount}
                onCancel={() => setCurrentTab('dashboard')}
                onLogout={() => {
                  logout();
                  setIsAuthenticated(false);
                  setCurrentTab('login');
                }}
              />
            </React.Suspense>
          );
        }
        return (
          <CreateInvoice
            invoices={activeInvoices}
            customers={activeCustomers}
            products={activeProducts}
            businessSettings={activeSettings}
            onSaveInvoice={handleSaveInvoice}
            setCurrentTab={setCurrentTab}
            editingInvoice={editingInvoice}
            onDownloadPDF={handleDownloadPDF}
            onBack={() => {
              setEditingInvoice(null);
              setCurrentTab('dashboard');
            }}
            onQuickBillOpen={() => setIsQuickBillOpen(true)}
          />
        );
      case 'guide':
        // Legacy fallback
        return (
          <HelpCenter />
        );
      case 'customers':
        return (
          <Customers
            customers={activeCustomers}
            invoices={activeInvoices}
            onSaveCustomer={handleSaveCustomer}
            onDeleteCustomer={handleDeleteCustomer}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
            onCreateBill={(cust) => {
              setEditingInvoice({ customerName: cust.name });
              setCurrentTab('create-invoice');
            }}
          />
        );
      case 'products':
        return (
          <Products
            products={activeProducts}
            onSaveProduct={handleSaveProduct}
            onDeleteProduct={handleDeleteProduct}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'expenses':
        return (
          <Expenses
            expenses={activeExpenses}
            onSaveExpense={handleSaveExpense}
            onDeleteExpense={handleDeleteExpense}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'appointments':
        return <Appointments />;
      case 'orders':
        return <Orders invoices={activeInvoices} customers={activeCustomers} businessSettings={activeSettings} setCurrentTab={setCurrentTab} />;
      case 'patients':
        return <Patients />;
      case 'students':
        if (activeSettings && !isEducationBusiness(activeSettings.defaultBillingTemplate)) {
          // If a Business workspace attempts to open /students, automatically redirect
          // We don't render Students, we redirect to customers
          setTimeout(() => setCurrentTab('customers'), 0);
          return <div className="min-h-screen flex items-center justify-center"><ClassicLoader /></div>;
        }
        return <Students />;
      case 'clients':
        return <Clients />;
      case 'measurements':
        return <Measurements />;
      case 'designBook':
        return <DesignBook />;
      case 'devices':
        return <Devices />;
      case 'serviceJobs':
        return <ServiceJobs />;
      case 'projects':
        return <Projects />;
      case 'delivery':
        return <Delivery />;
      case 'premium-upgrade':
        if (isMaintenanceMode || activeSettings?.disablePremiumUpgrade) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">Premium Upgrades Suspended</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                Upgrading to premium features is temporarily suspended by the administrator.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Back to Dashboard
              </button>
            </div>
          );
        }
        return (
          <Subscription
            currentSubscription={subscription}
            onUpgrade={handleSaveSubscription}
            businessSettings={activeSettings}
          />
        );
      case 'subscription':
        return (
          <Subscription
            currentSubscription={subscription}
            onUpgrade={handleSaveSubscription}
            businessSettings={activeSettings}
          />
        );

      case 'pdf-templates':
        if (isMaintenanceMode || activeSettings?.disableLiveLinkCreation) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">Customization Suspended</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                Template customization is temporarily suspended by the administrator.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Back to Dashboard
              </button>
            </div>
          );
        }
        return (
          <PdfTemplateStudio 
            businessSettings={settings} 
            setSettings={setSettings} 
            setCurrentTab={setCurrentTab}
            subscription={subscription}
          />
        );
      case 'live-link-templates':
        if (isMaintenanceMode || activeSettings?.disableLiveLinkCreation) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">Live Invoice Links Suspended</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                Live link customization and settings are temporarily suspended by the administrator.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Back to Dashboard
              </button>
            </div>
          );
        }
        return (
          <LiveLinkTemplateStudio 
            settings={settings}
            onSaveSettings={handleSaveSettings}
            subscription={subscription}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'marketplace':
        return (
          <TemplateMarketplace
            settings={settings}
            onSaveSettings={handleSaveSettings}
            subscription={subscription}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'design-studio':
        return (
          <DesignStudio setCurrentTab={setCurrentTab} />
        );
      case 'backup-restore':
        return (
          <BackupRestore
            settings={settings}
            invoices={invoices}
            customers={customers}
            products={products}
            expenses={expenses}
            onImportBackup={handleImportBackup}
          />
        );
      case 'more':
        return (
          <MoreMenu
            setCurrentTab={setCurrentTab}
            isAuthenticated={isAuthenticated}
            onLoginSuccess={handleLoginSuccess}
            businessSettings={settings}
            userRole={userRole}
            pendingPaymentsCount={pendingPayments.length}
          />
        );
      case 'privacy':
        return <PrivacyPolicy setCurrentTab={setCurrentTab} />;
      case 'terms':
        return <TermsOfService setCurrentTab={setCurrentTab} />;
      case 'refund':
        return <RefundPolicy setCurrentTab={setCurrentTab} />;
      case 'data-deletion':
        return <DataDeletion onBack={() => setCurrentTab('more')} />;
      case 'support':
        return <Support onBack={() => setCurrentTab('more')} />;
      case 'workspace-manager':
        return (
          <WorkspaceManager
            businessWorkspaces={businessWorkspaces}
            activeWorkspaceId={activeWorkspaceId}
            setActiveWorkspace={setActiveWorkspace}
            settings={activeSettings}
            onSaveSettings={handleSaveSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'settings': {
        const session = getAuthSession();
        return (
          <Settings
            settings={activeSettings}
            onSaveSettings={handleSaveSettings}
            isAdmin={isAdminUser(session)}
            onResetDemo={handleResetDemo}
            onImportBackup={handleImportBackup}
            invoices={activeInvoices}
            customers={activeCustomers}
            installPromptEvent={installPromptEvent}
            isAppInstalled={isAppInstalled}
            onInstallApp={handleInstallApp}
            subscription={subscription}
            setCurrentTab={setCurrentTab}
          />
        );
      }
      default:
        // Automatically recover from invalid tabs stored in localStorage
        setTimeout(() => setCurrentTab('dashboard'), 0);
        return (
          <div className="flex flex-col items-center justify-center h-full text-center p-10">
            <ClassicLoader />
            <p className="text-theme-muted font-bold mt-4 animate-pulse">Recovering workspace...</p>
          </div>
        );
    }
  };

  // Intercept for Public Invoice Loading/Display (No Auth Route Interceptor)
  if (loadingPublicInvoice) {
    return (
      <div className="min-h-screen bg-theme-main flex flex-col items-center justify-center p-6 text-center text-white font-sans">
        <ClassicLoader />
        <p className="text-theme-muted text-xs font-bold uppercase mt-4 tracking-widest animate-pulse">Loading secure digital invoice...</p>
      </div>
    );
  }

  if (publicToken) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <PublicInvoice initialInvoice={publicInvoice} />
      </React.Suspense>
    );
  }

  if (portalId) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <BillingPortal customerId={portalId} />
      </React.Suspense>
    );
  }

  if (eduPortalId) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <StudentPortal studentId={eduPortalId} />
      </React.Suspense>
    );
  }

  // Show onboarding/login if not authenticated
  const isDemoJourneyActive = localStorage.getItem('billqyro_demo_journey_mode') === 'true';
  const isDemoLoggedIn = localStorage.getItem('billqyro_demo_logged_in') === 'true';

  if (isDemoSessionActive && isDemoJourneyActive && !isDemoLoggedIn) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <DemoLogin onDemoLoginSuccess={() => {
          setIsAuthenticated(true);
          setShowWelcomeAnimation(true);
          window.dispatchEvent(new Event('storage'));
        }} />
      </React.Suspense>
    );
  }

  if (!isAuthenticated && (!isDemoSessionActive || !isDemoJourneyActive)) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <Landing onLoginSuccess={handleLoginSuccess} />
      </React.Suspense>
    );
  }

  // --- Account Blocked Interceptor ---
  if (settings?.blocked === true) {
    const session = getAuthSession();
    if (!isAdminUser(session)) {
      return (
        <div className="min-h-screen bg-theme-main flex flex-col items-center justify-center p-6 text-center font-sans text-white">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="max-w-md bg-theme-card p-8 rounded-3xl border border-theme-border-soft shadow-2xl space-y-6"
          >
            <div className="w-16 h-16 bg-theme-danger/20 text-theme-danger rounded-2xl flex items-center justify-center mx-auto shadow-lg shadow-rose-500/10">
              <Lock className="w-8 h-8" />
            </div>
            <h1 className="text-2xl font-black tracking-tight text-white">Account Deactivated</h1>
            <p className="text-theme-muted text-xs font-semibold leading-relaxed">
              Your BillQyro workspace has been temporarily blocked by the platform administrator due to policy guidelines or outstanding billing concerns.
            </p>
            <div className="p-4 bg-theme-surface/50 rounded-2xl border border-theme-border-soft/80 text-left space-y-2">
              <span className="text-[10px] text-theme-muted uppercase font-black block tracking-widest">Administrator Notice</span>
              <p className="text-[11px] text-theme-muted font-semibold leading-relaxed">
                If you believe this is an error or wish to request immediate reactivation, please contact support at <strong className="text-theme-accent select-all">{settings.email || 'support@billqyro.com'}</strong> or email your account manager directly.
              </p>
            </div>
            <button
              onClick={() => {
                logout();
                setIsAuthenticated(false);
              }}
              className="w-full py-3 bg-theme-card hover:bg-theme-surface text-white font-bold text-xs rounded-xl shadow-lg active:scale-[0.98] transition-all cursor-pointer uppercase tracking-wider"
            >
              Sign Out of Account
            </button>
          </motion.div>
        </div>
      );
    }
  }

  // --- Account Soft Lock Interceptor (Due Limit) ---
  const freeLimit = settings?.freeInvoiceLimit || 15;
  const pendingAmountLimit = settings?.maximumPendingDue || 100;
  const chargePerBill = settings?.chargePerBill || 5;
  
  if (subscription?.status !== 'premium' && invoices.length > freeLimit) {
    const chargeableBills = invoices.length - freeLimit;
    const pendingAmount = chargeableBills * chargePerBill;
    
    if (pendingAmount >= pendingAmountLimit) {
      const session = getAuthSession();
      if (!isAdminUser(session)) {
        return (
          <React.Suspense fallback={<div className="flex h-screen items-center justify-center"><ClassicLoader /></div>}>
            <PaymentDueScreen 
              pendingAmount={pendingAmount} 
              chargeableBills={chargeableBills}
              onLogout={() => {
                logout();
                setIsAuthenticated(false);
              }} 
            />
          </React.Suspense>
        );
      }
    }
  }

  // Root level maintenance mode interceptor removed to allow access to dashboard, invoices view, and backups.

  const path = window.location.pathname;
  const showAdminRoute = path === '/km-admin' || currentTab === 'admin-panel';

  return (
    <ErrorBoundary>
      <AnimatePresence mode="wait">
        {isAppBooting ? (
          <motion.div 
            key="global-loader"
            exit={{ opacity: 0, transition: { duration: 0.25, ease: 'easeOut' } }}
            className="fixed inset-0 z-[9999] bg-theme-main flex flex-col items-center justify-center font-sans"
          />
        ) : showAdminRoute ? (
          <motion.div key="admin-route" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="w-full h-full">
            <React.Suspense fallback={<div className="flex h-screen items-center justify-center"><ClassicLoader /></div>}>
              <AdminRouteGuard setCurrentTab={(tab) => {
                setCurrentTab(tab);
                if (window.location.pathname === '/km-admin') {
                  window.history.replaceState({}, '', '/');
                }
              }}>
                <AdminPanel 
                  currentTab={currentTab} 
                  setCurrentTab={(tab) => {
                    setCurrentTab(tab);
                    if (window.location.pathname === '/km-admin') {
                      window.history.replaceState({}, '', '/');
                    }
                  }} 
                />
              </AdminRouteGuard>
            </React.Suspense>
          </motion.div>
        ) : (
          <motion.div key="main-app" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.2 }} className="w-full h-full flex flex-col">
            {isDemoSessionActive && (
              <div className="bg-amber-500 text-amber-950 px-4 py-2 flex items-center justify-between font-bold text-sm z-[999999] relative shadow-md">
                <span className="flex items-center">
                  <AlertTriangle className="w-4 h-4 mr-2"/> DEMO MODE ACTIVE — Real data is safe. {isVideoCreatorMode && " | Video Creator Masking ON"}
                </span>
                <button onClick={() => {
                  if (window.confirm("Exit Demo Mode and return to Owner Test Lab?")) {
                    if (window.confirm("Do you want to clear the Demo Sandbox data as well?")) {
                      localStorage.removeItem('billqyro_demo_customers');
                      localStorage.removeItem('billqyro_demo_invoices');
                      localStorage.removeItem('billqyro_demo_products');
                      localStorage.removeItem('billqyro_demo_reports');
                      localStorage.removeItem('billqyro_demo_payments');
                      localStorage.removeItem('billqyro_demo_settings');
                      localStorage.removeItem('billqyro_demo_logged_in');
                    }
                    localStorage.removeItem('billqyro_demo_session_active');
                    localStorage.removeItem('billqyro_demo_journey_mode');
                    localStorage.removeItem('billqyro_demo_video_creator');
                    window.location.href = '/km-admin';
                  }
                }} className="bg-amber-950 hover:bg-amber-900 text-amber-500 px-3 py-1 rounded-md text-xs transition-colors">Exit Demo</button>
              </div>
            )}
            <PostLoginWelcome 
              show={showWelcomeAnimation} 
              userName={settings?.businessName || ''} 
              onComplete={() => setShowWelcomeAnimation(false)} 
            />
            {(currentTab === 'onboarding' || (activeSettings && !activeSettings.setupCompleted && !activeSettings.businessName)) ? (
              <OnboardingWizard 
                onComplete={() => setCurrentTab('dashboard')} 
                businessSettings={activeSettings} 
                onSaveSettings={(newSettings) => {
                  saveSettings(newSettings);
                  setSettings(newSettings);
                  setCurrentTab('dashboard');
                }}
                setCurrentTab={setCurrentTab}
              />
            ) : (
              <Layout
                currentTab={currentTab}
                setCurrentTab={(tab) => {
                  if (tab !== 'create-invoice') {
                    setEditingInvoice(null);
                  }
                  setCurrentTab(tab);
                }}
                onLogout={handleLogout}
                businessSettings={activeSettings}
                isAuthenticated={isAuthenticated}
                userRole={userRole}
                invoices={activeInvoices}
                subscription={subscription}
                userEmail={getAuthSession()?.userEmail}
                onQuickBillOpen={() => setIsQuickBillOpen(true)}
                pendingPaymentsCount={pendingPayments.length}
                businessWorkspaces={businessWorkspaces}
                activeWorkspaceId={activeWorkspaceId}
                setActiveWorkspace={setActiveWorkspace}
                syncSource={isDemoSessionActive ? "local" : "cloud"}
                syncStatus={isDemoSessionActive ? "Local Sandbox" : syncStatus}
              >
                <AnimatePresence mode="wait">
                  <motion.div
                    key={currentTab}
                    variants={pageVariants}
                    initial="initial"
                    animate="animate"
                    exit="exit"
                    className="w-full h-full flex flex-col"
                  >
                    <React.Suspense fallback={
                      <div className="flex flex-1 min-h-[calc(100vh-250px)] items-center justify-center">
                        <ClassicLoader text="Loading..." />
                      </div>
                    }>
                      {renderTabContent()}
                    </React.Suspense>
                  </motion.div>
                </AnimatePresence>
                
                <QuickBillModal 
                  isOpen={isQuickBillOpen}
                  onClose={() => setIsQuickBillOpen(false)}
                  onSave={handleSaveInvoice}
                  businessSettings={settings}
                  invoices={invoices}
                />
              </Layout>
            )}
            <Toaster
              position="bottom-center"
              toastOptions={{
                className: 'text-sm font-bold toast-above-nav',
                style: { borderRadius: '12px', background: '#fff', color: '#1e293b', marginBottom: 'calc(72px + env(safe-area-inset-bottom))' },
                success: { duration: 3000 },
                error: { duration: 4000 },
              }}
            />
            {/* Sync Badge moved to Layout Header */}
            
            {/* Paywall Modal */}
            <AnimatePresence>
              {showPaywallModal && (
                <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4">
                  <motion.div 
                    initial={{ opacity: 0 }} 
                    animate={{ opacity: 1 }} 
                    exit={{ opacity: 0 }} 
                    className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                    onClick={() => setShowPaywallModal(false)}
                  />
                  <motion.div
                    initial={{ scale: 0.95, opacity: 0, y: 20 }}
                    animate={{ scale: 1, opacity: 1, y: 0 }}
                    exit={{ scale: 0.95, opacity: 0, y: 20 }}
                    className="bg-theme-card relative z-10 w-full max-w-md p-8 rounded-3xl shadow-2xl border border-theme-border-soft text-center"
                  >
                    <div className="w-16 h-16 mx-auto bg-[image:var(--accent-gradient)] rounded-2xl flex items-center justify-center mb-6 shadow-glow">
                      <Lock className="w-8 h-8 text-white" />
                    </div>
                    <h2 className="text-2xl font-black text-theme-primary mb-2">Limit Reached</h2>
                    <p className="text-sm font-semibold text-theme-muted mb-6">
                      You've hit your free tier limit of {settings?.freeInvoiceLimit || 15} invoices. Upgrade to the Premium Plan for unlimited invoicing and exclusive SaaS features.
                    </p>
                    <div className="space-y-3">
                      <button
                        onClick={() => {
                          setShowPaywallModal(false);
                          setCurrentTab('subscription');
                        }}
                        className="w-full py-3.5 bg-[image:var(--accent-gradient)] text-white font-black uppercase tracking-wider rounded-xl hover:opacity-90 transition-all shadow-md active:scale-95"
                      >
                        Upgrade Now
                      </button>
                      <button
                        onClick={() => setShowPaywallModal(false)}
                        className="w-full py-3.5 bg-transparent border border-theme-border-soft text-theme-muted font-bold rounded-xl hover:text-theme-primary hover:bg-theme-surface transition-all active:scale-95"
                      >
                        Not Right Now
                      </button>
                    </div>
                  </motion.div>
                </div>
              )}
            </AnimatePresence>
          </motion.div>
        )}
      </AnimatePresence>
      {showConfetti && (
        <Confetti 
          width={window.innerWidth} 
          height={window.innerHeight} 
          recycle={false} 
          numberOfPieces={300} 
          gravity={0.15} 
          style={{ zIndex: 100000, position: 'fixed', top: 0, left: 0 }} 
        />
      )}
      <CommandPalette 
        isOpen={showCommandPalette} 
        onClose={() => setShowCommandPalette(false)} 
        onNavigate={(action) => {
          if (action.openQuickBill) {
            setIsQuickBillOpen(true);
          } else if (action.tab) {
            setCurrentTab(action.tab);
          }
        }} 
      />
    </ErrorBoundary>
  );
}

export default App;
