import React, { useState, useEffect } from 'react';
import toast, { Toaster } from 'react-hot-toast';
import { AnimatePresence, motion } from 'framer-motion';
import { Trash2, AlertTriangle, Lock, ServerCrash } from 'lucide-react';
import ClassicLoader from './components/ClassicLoader';
import PostLoginWelcome from './components/PostLoginWelcome';
import Layout from './components/Layout';
import { useThemeEngine } from './hooks/useThemeEngine';
import { 
  isDemoModeActive, 
  autoGenerateDemoDataIfNeeded, 
  getDemoInvoices, 
  getDemoCustomers, 
  getDemoProducts, 
  saveDemoInvoice, 
  deleteDemoInvoice, 
  saveDemoCustomer, 
  saveDemoProduct 
} from './utils/demoDataManager';
import { validatePayload, invoiceSchema, customerSchema } from './utils/validation';
import { calculateTotals } from './utils/invoiceUtils';
import { isEducationBusiness } from './config/businessPresets';
import { initializeStorage, getSettings as dbGetSettings } from './services/dbEngine';
import { useFeatureControl } from './hooks/useFeatureControl';

import { authEngine } from './services/authEngine';
import { settingsEngine } from './services/settingsEngine';
import { adminEngine } from './services/adminEngine';

import { invoiceEngine } from './services/invoiceEngine';
import { customerEngine } from './services/customerEngine';
import { staffEngine } from './services/staffEngine';
import { productEngine } from './services/productEngine';
import { expenseEngine } from './services/expenseEngine';
import { backupEngine } from './services/backupEngine';
import { subscriptionEngine } from './services/subscriptionEngine';
import { paymentEngine } from './services/paymentEngine';

import { downloadInvoicePDF, downloadInvoiceImage } from './utils/pdfUtils';
import { auth, firebaseReady } from './services/firebaseConfig';
import { onAuthStateChanged } from 'firebase/auth';
import { triggerSuccessFeedback, triggerPaymentSuccessFeedback, triggerPopFeedback, triggerDeleteFeedback, triggerVoiceFeedback } from './utils/feedback';
import { sendEmpireEvent, sendEmpireError, sendEmpireHealth } from './services/empireAgent';
import { collection, query, where, onSnapshot } from 'firebase/firestore';
import { db } from './services/firebaseConfig';
import { workspaceEngine } from './services/workspaceEngine';
import { securityEngine } from './services/securityEngine';
import QuickBillModal from './components/QuickBillModal';
import AdminPINLogin from './pages/admin/AdminPINLogin';
import Confetti from 'react-confetti';
import CommandPalette from './components/CommandPalette';
import { pageVariants } from './utils/animations';

const Landing = React.lazy(() => import('./pages/Landing'));

const DemoLogin = React.lazy(() => import('./pages/DemoLogin'));
const OnboardingWizard = React.lazy(() => import('./pages/onboarding/OnboardingWizard'));
const Dashboard = React.lazy(() => import('./pages/Dashboard'));
const Invoices = React.lazy(() => import('./pages/Invoices'));
const Estimates = React.lazy(() => import('./pages/Estimates'));
const PdfTemplateStudio = React.lazy(() => import('./pages/PdfTemplateStudio'));
const LiveLinkTemplateStudio = React.lazy(() => import('./pages/LiveLinkTemplateStudio'));
const CreateInvoice = React.lazy(() => import('./pages/CreateInvoice'));
const HelpCenter = React.lazy(() => import('./pages/HelpCenter'));
const Customers = React.lazy(() => import('./pages/Customers'));
const Products = React.lazy(() => import('./pages/Products'));
const StudioLayout = React.lazy(() => import('./pages/studios/StudioLayout'));
const Expenses = React.lazy(() => import('./pages/Expenses'));
const MoreMenu = React.lazy(() => import('./pages/MoreMenu'));
const PublicInvoice = React.lazy(() => import('./pages/PublicInvoice'));
const PendingPayments = React.lazy(() => import('./pages/PendingPayments'));
const DueLedger = React.lazy(() => import('./pages/DueLedger'));
const StaffLedger = React.lazy(() => import('./pages/StaffLedger'));
const TemplateMarketplace = React.lazy(() => import('./pages/TemplateMarketplace'));
const DesignStudio = React.lazy(() => import('./pages/DesignStudio'));
const BackupRestore = React.lazy(() => import('./pages/BackupRestore'));
const Reports = React.lazy(() => import('./pages/Reports'));
const PrivacyPolicy = React.lazy(() => import('./pages/PrivacyPolicy'));
const TermsOfService = React.lazy(() => import('./pages/TermsOfService'));
const RefundPolicy = React.lazy(() => import('./pages/RefundPolicy'));
const DataDeletion = React.lazy(() => import('./pages/DataDeletion'));
const Support = React.lazy(() => import('./pages/Support'));
const SystemHealth = React.lazy(() => import('./pages/SystemHealth'));
const AuditLogs = React.lazy(() => import('./pages/AuditLogs'));
const InternalBank = React.lazy(() => import('./pages/InternalBank'));
const WorkspaceManager = React.lazy(() => import('./pages/WorkspaceManager'));
const Appointments = React.lazy(() => import('./pages/Appointments'));
const Orders = React.lazy(() => import('./pages/Orders'));
const Patients = React.lazy(() => import('./pages/business/Patients'));
const Students = React.lazy(() => import('./pages/business/Students'));
const Clients = React.lazy(() => import('./pages/business/Clients'));
const Measurements = React.lazy(() => import('./pages/business/Measurements'));
const DesignBook = React.lazy(() => import('./pages/business/DesignBook'));
const Devices = React.lazy(() => import('./pages/business/Devices'));
const ServiceJobs = React.lazy(() => import('./pages/business/ServiceJobs'));
const Projects = React.lazy(() => import('./pages/business/Projects'));
const Delivery = React.lazy(() => import('./pages/business/Delivery'));
const AdminPanel = React.lazy(() => import('./pages/admin/AdminPanel'));
const CyberDashboard = React.lazy(() => import('./pages/cybercafe/CyberDashboard'));
const PortalHub = React.lazy(() => import('./pages/cybercafe/PortalHub'));
const QuickToolsCenter = React.lazy(() => import('./pages/cybercafe/QuickToolsCenter'));
const CustomerRegister = React.lazy(() => import('./pages/cybercafe/CustomerRegister'));
const CashManagement = React.lazy(() => import('./pages/cybercafe/CashManagement'));
const PaymentDueScreen = React.lazy(() => import('./pages/PaymentDueScreen'));
const SandboxAdmin = React.lazy(() => import('./pages/admin/SandboxAdmin'));
const StudentPortal = React.lazy(() => import('./pages/StudentPortal'));
const CustomerWorkspace = React.lazy(() => import('./pages/CustomerWorkspace'));
const CustomerPortalConfig = React.lazy(() => import('./pages/CustomerPortalConfig'));
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false, error: null, errorInfo: null };
  }

  static getDerivedStateFromError(error) {
    return { hasError: true, error };
  }

  componentDidCatch(error, errorInfo) {
    console.error("ErrorBoundary caught an error", error, errorInfo);
    
    // Automatically reload on Vite dynamic import failure (new deployment pushed)
    if (error && error.message && error.message.includes('Failed to fetch dynamically imported module')) {
      if (!sessionStorage.getItem('billqyro_chunk_failed_reload')) {
        sessionStorage.setItem('billqyro_chunk_failed_reload', 'true');
        window.location.reload();
        return;
      }
    }
    
    sendEmpireError({
      errorType: "app_crash",
      message: error?.toString() || "Unknown error",
      severity: "Critical",
      page: window.location.pathname
    });

    this.setState({ errorInfo });
  }

  render() {
    if (this.state.hasError) {
      return (
        <div style={{ padding: '20px', backgroundColor: '#fee2e2', color: '#991b1b', minHeight: '100vh', fontFamily: 'system-ui' }}>
          <h1 style={{ fontSize: '24px', fontWeight: 'bold' }}>Something went wrong.</h1>
          <p style={{ marginTop: '10px', fontWeight: 'bold' }}>Error: {this.state.error?.toString()}</p>
          <pre style={{ marginTop: '20px', padding: '10px', backgroundColor: '#fecaca', overflowX: 'auto', fontSize: '12px' }}>
            {this.state.errorInfo?.componentStack}
          </pre>
          <button onClick={() => window.location.reload()} style={{ marginTop: '20px', padding: '10px 20px', backgroundColor: '#dc2626', color: 'white', borderRadius: '5px', cursor: 'pointer' }}>
            Reload Page
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}



const AdminRouteGuard = ({ setCurrentTab, children }) => {
  const session = authEngine.getAuthSession();
  const [isUnlocked, setIsUnlocked] = useState(
    localStorage.getItem('billqyro_admin_unlocked') === 'true'
  );

  // The user is prompted for a PIN if they are not a superadmin.
  // The AdminPINLogin handles the lockout and cancel logic.

  // If not admin and not unlocked, show PIN login
  if (!adminEngine.isAdminUser(session) && !isUnlocked) {
    return (
      <AdminPINLogin
        onPinSuccess={() => setIsUnlocked(true)}
        onCancel={() => setCurrentTab('dashboard')}
      />
    );
  }

  return children;
};

function App() {

  // --- STATE SYSTEM (must be declared before any useEffect that references them) ---
  const [showWelcomeAnimation, setShowWelcomeAnimation] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const [showCommandPalette, setShowCommandPalette] = useState(false);

  useEffect(() => {
    const handleConfetti = () => {
      setShowConfetti(true);
      setTimeout(() => setShowConfetti(false), 5000);
    };
    const handleCommandPalette = () => {
      setShowCommandPalette(true);
    };
    window.addEventListener('trigger-confetti', handleConfetti);
    window.addEventListener('open-command-palette', handleCommandPalette);
    return () => {
      window.removeEventListener('trigger-confetti', handleConfetti);
      window.removeEventListener('open-command-palette', handleCommandPalette);
    };
  }, []);

  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    const realAuth = !!authEngine.getAuthSession();
    const demoAuth = localStorage.getItem('billqyro_demo_session_active') === 'true' && 
                     localStorage.getItem('billqyro_demo_journey_mode') === 'true' && 
                     localStorage.getItem('billqyro_demo_logged_in') === 'true';
    return realAuth || demoAuth;
  });
  const [syncStatus, setSyncStatus] = useState('Synced');
  const [isDemoSessionActive, setIsDemoSessionActive] = useState(false);
  const [isVideoCreatorMode, setIsVideoCreatorMode] = useState(false);
  const [globalMaintenanceMode, setGlobalMaintenanceMode] = useState(false);
  
  const [demoInvoices, setDemoInvoices] = useState([]);
  const [demoCustomers, setDemoCustomers] = useState([]);
  const [demoStaffs, setDemoStaffs] = useState([]);
  const [demoProducts, setDemoProducts] = useState([]);
  const [demoExpenses] = useState([]);
  const [demoSettings, setDemoSettings] = useState(null);

  useEffect(() => {
    const checkDemo = () => {
      const active = isDemoModeActive();
      setIsDemoSessionActive(active);
      const isVideo = localStorage.getItem('billqyro_demo_video_creator') === 'true';
      setIsVideoCreatorMode(isVideo);
      
      if (active) {
        autoGenerateDemoDataIfNeeded();
        setDemoInvoices(getDemoInvoices());
        setDemoCustomers(getDemoCustomers());
        setDemoProducts(getDemoProducts());
        
        // Reports / settings
        const s = JSON.parse(localStorage.getItem('billqyro_demo_settings') || 'null');
        setDemoSettings(s || {
           businessName: isVideo ? 'Demo Corp' : 'My Business (Demo)',
           ownerName: isVideo ? 'Demo Owner' : 'Me',
           email: isVideo ? 'hello@democorp.com' : 'demo@example.com',
           phone: isVideo ? '+1 555-0199' : '9999999999',
           themeColor: 'obsidian-gold'
        });
      }
    };
    checkDemo();
    window.addEventListener('storage', checkDemo);
    return () => window.removeEventListener('storage', checkDemo);
  }, []);

  const [currentTab, setCurrentTab] = useState(() => {
    if (window.location.pathname === '/km-admin') {
      return 'admin-panel';
    }
    const saved = localStorage.getItem('billqyro_last_route');
    const isAuth = !!authEngine.getAuthSession() || (localStorage.getItem('billqyro_demo_session_active') === 'true' && localStorage.getItem('billqyro_demo_journey_mode') === 'true' && localStorage.getItem('billqyro_demo_logged_in') === 'true');
    if (isAuth && saved && saved !== 'admin-panel') {
      return saved;
    }
    if (!isAuth) return 'landing';
    return null; // Neutral boot state - resolved centrally by the app gate
  });

  useEffect(() => {
    if (currentTab && currentTab !== 'landing') {
      localStorage.setItem('billqyro_last_route', currentTab);
    }
    
    // Sync URL for km-admin to act like a real route
    if (currentTab === 'admin-panel') {
      window.history.replaceState({}, '', '/km-admin');
    } else if (window.location.pathname === '/km-admin') {
      window.history.replaceState({}, '', '/');
    }

    sendEmpireEvent({
      eventType: "page_view",
      message: `Navigated to ${currentTab}`,
      page: currentTab
    });
  }, [currentTab]);

  const [userRole, setUserRole] = useState(() => localStorage.getItem('billqyro_user_role') || 'user');
  const [userPermissions, setUserPermissions] = useState(null);
  const [workspaceVerified, setWorkspaceVerified] = useState(false);

  // Capacitor Android Back Button Handler
  useEffect(() => {
    import('@capacitor/app').then(({ App: CapApp }) => {
      CapApp.removeAllListeners('backButton');
      CapApp.addListener('backButton', () => {
        setCurrentTab((prevTab) => {
          if (prevTab !== 'dashboard') {
            return 'dashboard';
          } else {
            CapApp.exitApp();
            return prevTab;
          }
        });
      });
    }).catch(() => { /* not in capacitor env */ });
  }, []);


  // Boot Interceptor for Public Invoice
  const [publicInvoice, setPublicInvoice] = useState(null);
  const [loadingPublicInvoice, setLoadingPublicInvoice] = useState(false);
  const [publicToken, setPublicToken] = useState(null);

  useEffect(() => {
    const path = window.location.pathname;
    const publicTokenMatch = path.match(/^\/invoice\/([a-zA-Z0-9_-]+)/);
    const urlParams = new URLSearchParams(window.location.search);
    const tokenFromQuery = urlParams.get('uuid') || urlParams.get('i');
    const token = (publicTokenMatch ? publicTokenMatch[1] : null) || tokenFromQuery;

    if (token) {
      setPublicToken(token);
      setLoadingPublicInvoice(true);
      import('./services/invoiceEngine').then(({ invoiceEngine }) => { invoiceEngine.getInvoiceByPublicToken(token).then((inv) => {
          setPublicInvoice(inv);
          setLoadingPublicInvoice(false);
        });
      });
    }
  }, []);

  // Boot Interceptor for Portals
  const [portalId, setPortalId] = useState(null);
  const [eduPortalId, setEduPortalId] = useState(null);

  useEffect(() => {
    const path = window.location.pathname;
    
    // Strict redirect for Business workspaces trying to access student paths
    if (path === '/student' || path === '/students' || path.startsWith('/student/')) {
       const id = path.split('/')[2];
       if (id) {
         window.history.replaceState({}, '', `/billing/${id}`);
       } else {
         window.history.replaceState({}, '', '/billing');
       }
    }
    
    const newPath = window.location.pathname;

    const studentMatchLegacy = newPath.match(/^\/student\/(.+)/);
    const customerMatch = newPath.match(/^\/customer\/(.+)/);
    const portalMatch = newPath.match(/^\/portal\/(.+)/);
    const billingMatch = newPath.match(/^\/billing\/(.+)/);
    const eduPortalMatch = newPath.match(/^\/student-portal\/(.+)/);
    
    if (eduPortalMatch) {
      setEduPortalId(decodeURIComponent(eduPortalMatch[1]));
    } else if (customerMatch) {
      setPortalId(decodeURIComponent(customerMatch[1]));
    } else if (portalMatch) {
      setPortalId(decodeURIComponent(portalMatch[1]));
    } else if (billingMatch) {
      setPortalId(decodeURIComponent(billingMatch[1]));
    } else if (studentMatchLegacy) {
      setPortalId(decodeURIComponent(studentMatchLegacy[1]));
    } else if (newPath === '/customer' || newPath === '/portal') {
      // Allow access without ID, CustomerWorkspace handles prompt
      setPortalId('verification-pending'); 
    }
  }, []);

  // Storage states
  const [invoices, setInvoices] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [staffs, setStaffs] = useState([]);
  const [products, setProducts] = useState([]);
  // Settings with workspace support
  const [settings, setSettings] = useState(() => {
    const s = dbGetSettings() || {};
    if (!s.businessWorkspaces) {
      // Initialize default workspace
      const defaultWs = {
        id: 'ws_default_001',
        name: 'Default Workspace',
        type: 'default',
        enabledModules: ['billing', 'customers', 'products', 'dueLedger', 'reports'],
      };
      s.businessWorkspaces = [defaultWs];
      s.activeWorkspaceId = defaultWs.id;
    } else if (!s.activeWorkspaceId && s.businessWorkspaces.length) {
      s.activeWorkspaceId = s.businessWorkspaces[0].id;
    }
    // Do not call settingsEngine.saveSettings(s) here, as it may queue an offline sync
    // that overwrites the user's cloud settings before syncFromFirestore downloads them.
    // The defaults will live in memory until the user completes onboarding.
    return s;
  });

  // PHASE 2 AUTH STABILIZATION: Removed reactive boot-time redirect to prevent Dashboard flash


  const [expenses, setExpenses] = useState([]);
  const [students, setStudents] = useState([]);
  const [subscription, setSubscription] = useState(() => subscriptionEngine.getSubscriptionDetailsSync({}));
  const [revenueStatus, setRevenueStatus] = useState({
    totalBillsCreated: 0,
    freeBillsUsed: 0,
    billableBillsCount: 0,
    platformDueAmount: 0,
    platformPaidAmount: 0,
    platformPendingAmount: 0,
    lastPlatformPaymentDate: null,
    lockStatus: 'none',
    graceStatus: 'none',
    premiumStatus: 'free'
  });

  useEffect(() => {
    const fetchRevenue = async () => {
      const session = authEngine.getAuthSession();
      const userId = session?.uid || authEngine.getRealUserId() || 'local-user';
      try {
        const subDetails = await subscriptionEngine.getSubscriptionDetails();
        setSubscription(subDetails);
        const status = await paymentEngine.getUserRevenueState(userId, invoices, subDetails);
        setRevenueStatus(status);
      } catch (e) {
        console.error('Failed to load user revenue status:', e);
      }
    };
    fetchRevenue();
  }, [invoices, subscription, isAuthenticated]);
  // Workspace state
  const safeSettings = settings || {};
  const safeWorkspaces = safeSettings.businessWorkspaces || [];
  
  const [businessWorkspaces, setBusinessWorkspaces] = useState(safeWorkspaces);
  const [activeWorkspaceId, setActiveWorkspaceId] = useState(safeSettings.activeWorkspaceId || (safeWorkspaces.length > 0 ? safeWorkspaces[0].id : null));
  
  // Feature Control Engine Integration
  const { isFeatureEnabled, loading: featuresLoading } = useFeatureControl(activeWorkspaceId || settings?.activeWorkspaceId);

  // Keep workspaces in sync with cloud settings updates
  useEffect(() => {
    const currentSafeSettings = settings || {};
    const currentSafeWorkspaces = currentSafeSettings.businessWorkspaces || [];
    
    if (currentSafeSettings.businessWorkspaces && JSON.stringify(currentSafeWorkspaces) !== JSON.stringify(businessWorkspaces)) {
      setBusinessWorkspaces(currentSafeWorkspaces);
    }
    if (currentSafeSettings.activeWorkspaceId && currentSafeSettings.activeWorkspaceId !== activeWorkspaceId) {
      setActiveWorkspaceId(currentSafeSettings.activeWorkspaceId);
    }
  }, [settings, businessWorkspaces, activeWorkspaceId]);

  // Handle local workspace changes
  const updateWorkspaceState = (newWorkspaces, newActiveId) => {
    setBusinessWorkspaces(newWorkspaces);
    setActiveWorkspaceId(newActiveId);
    const updated = { ...(settings || {}), businessWorkspaces: newWorkspaces, activeWorkspaceId: newActiveId };
    setSettings(updated);
    settingsEngine.saveSettings(updated);
    window.dispatchEvent(new CustomEvent('billqyro_sync'));
  };

  const setActiveWorkspace = (id) => {
    updateWorkspaceState(businessWorkspaces, id);
  };

  // Real-time Pending Payments state
  const [pendingPayments, setPendingPayments] = useState([]);
  
  useEffect(() => {
    if (!isAuthenticated || !db || !auth) return;
    
    let unsubscribe = () => {};
    
    // Listen for auth state changes to get current user UID
    const authUnsubscribe = onAuthStateChanged(auth, (user) => {
      if (user) {
        const q = query(
          collection(db, 'payment_proofs'),
          where('ownerId', '==', user.uid),
          where('status', '==', 'pending')
        );
        
        unsubscribe = onSnapshot(q, (snapshot) => {
          const proofs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
          setPendingPayments(proofs);
        });
      } else {
        setPendingPayments([]);
      }
    });
    
    return () => {
      authUnsubscribe();
      unsubscribe();
    };
  }, [isAuthenticated]);
  
  // --- 🚀 GLOBAL BOOT & LOADING STATE ---
  const [isAppBooting, setIsAppBooting] = useState(true);
  const [isDataHydrating, setIsDataHydrating] = useState(true);
  const [cloudSyncDone, setCloudSyncDone] = useState(false);

  // Safety timeout to ensure app never gets stuck on boot screen
  useEffect(() => {
    if (isAppBooting) {
      const timeout = setTimeout(() => {
        console.warn('[BOOT TIMEOUT] 3000ms reached, forcing app load.');
        setIsAppBooting(false);
      }, 3000);
      return () => clearTimeout(timeout);
    }
  }, [isAppBooting]);

  // Async Data Loader & Boot Sequence
  useEffect(() => {
    let isBooted = false;

    const loadLocalData = async () => {
      sendEmpireEvent({ eventType: "app_opened", message: "BillQyro Web App Opened", page: "init" });
      sendEmpireHealth({ status: "Healthy", healthScore: 100, note: "App initialized successfully" });
      
      try {
        setInvoices(await invoiceEngine.getInvoices() || []);
        setCustomers(await customerEngine.getCustomers() || []);
        setStaffs(await staffEngine.getStaffs() || []);
        setProducts(await productEngine.getProducts() || []);
        setStudents(await customerEngine.getCustomers() || []);
        setExpenses(await expenseEngine.getExpenses() || []);
      } catch (err) {
        console.error("Error loading local data:", err);
      } finally {
        setIsDataHydrating(false);
        isBooted = true;
        setIsAppBooting(false);
      }
    };
    loadLocalData();

    const handleSync = async () => {
      if (!isBooted) return;
      try {
        setInvoices(await invoiceEngine.getInvoices() || []);
        setCustomers(await customerEngine.getCustomers() || []);
        setStaffs(await staffEngine.getStaffs() || []);
        setProducts(await productEngine.getProducts() || []);
        setStudents(await customerEngine.getCustomers() || []);
        setExpenses(await expenseEngine.getExpenses() || []);
        const latestSettings = await settingsEngine.getSettings();
        if (latestSettings) {
          if (adminEngine.isAdminUser(authEngine.getAuthSession()) && latestSettings.maintenanceMode) {
            const cleaned = { ...latestSettings };
            delete cleaned.maintenanceMode;
            setSettings(cleaned);
            settingsEngine.saveSettings(cleaned);
          } else {
            setSettings(latestSettings);
          }
        }
        const updatedSub = await subscriptionEngine.getSubscriptionDetails();
        setSubscription(updatedSub);
      } catch (err) {
        console.error("Error reloading data on sync:", err);
      }
    };
    window.addEventListener('billqyro_sync', handleSync);
    
    // --- Pro Sync Engine Event Bus ---
    const handleSettingsUpdated = (e) => {
      if (e.detail) setSettings(e.detail);
    };
    const handleDataUpdated = async (e) => {
      const col = e.detail?.collectionName;
      if (col === 'invoices') setInvoices(await invoiceEngine.getInvoices() || []);
      if (col === 'customers') setCustomers(await customerEngine.getCustomers() || []);
        setStaffs(await staffEngine.getStaffs() || []);
      if (col === 'products') setProducts(await productEngine.getProducts() || []);
      if (col === 'students') setStudents(await customerEngine.getCustomers() || []);
      if (col === 'bankLedger' || col === 'bankCredit') {
        window.dispatchEvent(new CustomEvent('billqyro_bank_updated'));
      }
    };
    const handleSyncStatus = (e) => {
      if (e.detail) setSyncStatus(e.detail);
    };
    window.addEventListener('billqyro:settings-updated', handleSettingsUpdated);
    window.addEventListener('billqyro:data-updated', handleDataUpdated);
    window.addEventListener('billqyro:sync-status', handleSyncStatus);
    
    const handleNavigate = (e) => {
      if (e.detail) {
        setCurrentTab(e.detail);
      }
    };
    window.addEventListener('navigate_tab', handleNavigate);

    return () => {
      window.removeEventListener('billqyro_sync', handleSync);
      window.removeEventListener('billqyro:settings-updated', handleSettingsUpdated);
      window.removeEventListener('billqyro:data-updated', handleDataUpdated);
      window.removeEventListener('billqyro:sync-status', handleSyncStatus);
      window.removeEventListener('navigate_tab', handleNavigate);
    };
  }, []);

  // Workspace Contexts
  const [editingInvoice, setEditingInvoice] = useState(null);
  const [showPaywallModal, setShowPaywallModal] = useState(false);

  // PWA Installer States
  const [installPromptEvent, setInstallPromptEvent] = useState(null);
  const [isAppInstalled, setIsAppInstalled] = useState(false);
  const [isQuickBillOpen, setIsQuickBillOpen] = useState(false);

  // Initialize Smart SVG Dynamic Theme Engine
  useThemeEngine(settings);

  useEffect(() => {
    const handleBeforeInstallPrompt = (e) => {
      e.preventDefault();
      setInstallPromptEvent(e);
      // PWA install prompt stashed
    };

    const handleAppInstalled = () => {
      setInstallPromptEvent(null);
      setIsAppInstalled(true);
      toast.success('🎉 BillQyro App installed successfully!');
    };

    window.addEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
    window.addEventListener('appinstalled', handleAppInstalled);

    if (window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true) {
      setIsAppInstalled(true);
    }

    return () => {
      window.removeEventListener('beforeinstallprompt', handleBeforeInstallPrompt);
      window.removeEventListener('appinstalled', handleAppInstalled);
    };
  }, []);

  const handleInstallApp = async () => {
    if (!installPromptEvent) return;
    installPromptEvent.prompt();
    const { outcome } = await installPromptEvent.userChoice;
    // User install choice handled
    setInstallPromptEvent(null);
  };

  // --- EFFECTS ---

  // Initialize Database on App mount
  useEffect(() => {
    initializeStorage();
  }, []);

  // Listen to Firebase Auth state
  useEffect(() => {
    if (firebaseReady && auth) {
      const unsubscribe = onAuthStateChanged(auth, async (user) => {
        // Firebase auth state updated
        if (user) {
          const tokenResult = await user.getIdTokenResult();
          const session = authEngine.getAuthSession();
          const newSession = {
            timestamp: Date.now(),
            token: 'billqyro-secure-session',
            userEmail: user.email || '',
            uid: user.uid,
            isSuperAdmin: !!tokenResult.claims.superAdmin
          };
          localStorage.setItem('billqyro_auth', JSON.stringify(newSession));
          setIsAuthenticated(true);
          const role = localStorage.getItem('billqyro_user_role') || 'user';
          setUserRole(role);

          // AUTH → WORKSPACE VERIFICATION → PERMISSION CHECK → DASHBOARD
          try {
            const currentWs = await workspaceEngine.getCurrent();
            const verified = await workspaceEngine.verifyAccess(user.uid, currentWs.id);
            setWorkspaceVerified(verified.authorized);
            if (!verified.authorized) {
              console.warn('[AuthFlow] Workspace verification failed:', verified.reason);
            }
            const permissions = await securityEngine.getPermissions(user.uid);
            setUserPermissions(permissions);
            localStorage.setItem('billqyro_user_permissions', JSON.stringify(permissions));
          } catch (e) {
            console.warn('[AuthFlow] Workspace/perm check failed:', e);
            setWorkspaceVerified(true);
            setUserPermissions(null);
          }
        } else {
          setIsAuthenticated(false);
          setWorkspaceVerified(false);
          setUserPermissions(null);
          setIsAppBooting(false);
          setIsDataHydrating(false);
        }
      });
      return () => unsubscribe();
    } else {
      setIsAppBooting(false);
      setIsDataHydrating(false);
    }
  }, []);

  // Sync from Firebase Firestore when authenticated
  useEffect(() => {
    if (isAuthenticated) {
      const currentUserId = authEngine.getAuthSession()?.uid;
      const runSync = async () => {
        try {
          const synced = await invoiceEngine.syncFromCloud();
          
          // Additive: pull + merge Internal Bank data (fire-and-forget, failure-isolated).
          import('./services/bankEngine').then(({ bankEngine }) => bankEngine.syncFromCloud(true)).catch((e) => {
            console.warn('[BANK SYNC] Startup pull skipped:', e);
          });
          
          if (currentUserId !== authEngine.getAuthSession()?.uid) {
            console.warn('[Session Guard] Stale sync aborted due to session change');
            return;
          }
          
          if (synced) {
            if (synced.invoices) setInvoices(synced.invoices);
            if (synced.customers) setCustomers(synced.customers);
            if (synced.products) setProducts(synced.products);
            if (synced.settings) setSettings(synced.settings);
            if (synced.expenses) setExpenses(synced.expenses);
            if (synced.subscription) setSubscription(synced.subscription);
          }
          
          // Fetch global admin settings for defaults
          try {
            const adminGlobal = await adminEngine.getGlobalAdminSettings();
            if (adminGlobal) {
              if (adminGlobal.defaultTheme) {
                localStorage.setItem('billqyro_admin_default_theme', adminGlobal.defaultTheme);
                if (!synced?.settings?.themeColor && !synced?.settings?.brandColor) {
                  // Handled by ThemeContext
                  import('./utils/themeIcon').then(m => m.updateFaviconForTheme(adminGlobal.defaultTheme));
                }
              }
              if (adminGlobal.defaultMode) {
                localStorage.setItem('billqyro_admin_default_mode', adminGlobal.defaultMode);
                if (!synced?.settings?.displayMode) {
                  // Handled by ThemeContext
                }
              }
            }
          } catch { console.warn('Could not fetch admin settings on boot.'); }

          try {
            const ann = await adminEngine.getActiveAnnouncement();
            if (ann && ann.type === 'maintenance') {
              setGlobalMaintenanceMode(true);
            } else {
              setGlobalMaintenanceMode(false);
            }
          } catch { console.warn('Could not fetch active announcement on boot.'); }

          // Enable real-time multi-device sync via new Sync Engine
          import('./services/syncEngine').then(({ startRealTimeSync }) => {
            const userId = auth.currentUser?.uid;
            if (userId) {
              startRealTimeSync(userId, (newSettings) => {
                setSettings(newSettings);
              });
            }
          });
        } catch {
          sendEmpireError({ errorType: "sync_failed", message: "Could not sync Firestore on startup", severity: "Medium" });
          console.warn('Could not sync Firestore on startup. Falling back to LocalStorage.', e);
        } finally {
          setIsAppBooting(false); // ALWAYS EXIT BOOT
          setCloudSyncDone(true);
        }
      };
      runSync();
    }
  }, [isAuthenticated]);



  // --- AUTH BRIDGE ---
  const handleLoginSuccess = () => {
    if (!sessionStorage.getItem('billqyro_welcome_shown')) {
      setShowWelcomeAnimation(true);
      sessionStorage.setItem('billqyro_welcome_shown', 'true');
    }
    // Yield route control to the Central App Gate
    setCurrentTab(null);
  };

  // Handle Legacy User Silent Upgrade (No redirects)
  useEffect(() => {
    if (isAuthenticated && !isAppBooting && settings && cloudSyncDone) {
      const isLegacyConfigured = !!(settings.businessName && settings.businessName.trim());
      if (!settings.setupCompleted && isLegacyConfigured) {
        const updated = { ...settings, setupCompleted: true };
        settingsEngine.saveSettings(updated);
        setSettings(updated);
      }
    }
  }, [isAuthenticated, isAppBooting, settings, cloudSyncDone]);

  const handleLogout = async () => {
    // 1. Instantly log out visually
    setUserRole('user');
    setIsAuthenticated(false);
    setCurrentTab('landing');
    
    // 2. Perform slow background network/db cleanup
    try {
      if (firebaseReady && auth) {
        await auth.signOut();
      }
    } catch (err) {
      console.error('Firebase sign out error', err);
    }
    
    try {
      // NOTE: IndexedDB operations can hang indefinitely if other tabs hold locks.
      // This is now non-blocking for the UI.
      authEngine.logout().catch(err => console.error('Auth engine logout error', err));
    } catch (err) {
      console.error('Auth engine logout error', err);
    }
    
    localStorage.removeItem('billqyro_user_role');
    localStorage.removeItem('billqyro_admin_unlocked');
    
    // STRICT MEMORY WIPE
    setSettings({});
    setBusinessWorkspaces([]);
    setActiveWorkspaceId(null);
    setInvoices([]);
    setCustomers([]);
    setProducts([]);
    setExpenses([]);
    setPendingPayments([]);
    setStudents([]);
    subscriptionEngine.getSubscriptionDetails().then(setSubscription);
    
    // RESET GLOBAL DOM THEME
    window.dispatchEvent(new CustomEvent('billqyro:settings-updated', { detail: {} }));
  };

  // --- DATA SYNCHRONIZERS ---

  // Invoices
  const handleSaveInvoice = async (payload, saveCustomerAsNew = false, isSilent = false) => {
    const targetInvoices = isDemoSessionActive ? demoInvoices : invoices;

    // Flatten nested InvoiceContext state if present
    if (payload.customer && typeof payload.customer === 'object') {
      payload.customerId = payload.customer.id || payload.customerId;
      payload.customerName = payload.customer.name || payload.customerName;
      payload.customerPhone = payload.customer.phone || payload.customerPhone;
      payload.customerEmail = payload.customer.email || payload.customerEmail;
      payload.customerAddress = payload.customer.address || payload.customerAddress;
      delete payload.customer;
    }

    // CRITICAL FIX: Merge payload with existing invoice to preserve fields like createdAt, publicToken, paymentHistory that sparse payloads drop
    if (payload.id) {
      const existing = targetInvoices.find(inv => inv.id === payload.id);
      if (existing) {
        payload = { ...existing, ...payload };
      }
    }
    if (payload.totals && typeof payload.totals === 'object') {
      payload.subtotal = payload.totals.subtotal || payload.subtotal || 0;
      payload.taxPercentage = payload.totals.taxPercentage ?? payload.taxPercentage ?? 18;
      payload.taxAmount = payload.totals.taxAmount || payload.taxAmount || 0;
      payload.discountAmount = payload.totals.discountAmount || payload.discountAmount || 0;
      payload.grandTotal = payload.totals.grandTotal || payload.grandTotal || 0;
      payload.amountPaid = payload.totals.amountPaid || payload.amountPaid || 0;
      payload.balanceDue = payload.totals.balanceDue || payload.balanceDue || 0;
      delete payload.totals;
    }
    if (payload.settings && typeof payload.settings === 'object') {
      payload.notes = payload.settings.notes || payload.notes || '';
      payload.terms = payload.settings.terms || payload.terms || '';
      payload.paymentStatus = payload.settings.paymentStatus || payload.paymentStatus || 'Unpaid';
      payload.orderStatus = payload.settings.orderStatus || payload.orderStatus || 'Pending';
      payload.paymentMethod = payload.settings.paymentMethod || payload.paymentMethod || 'Cash';
      payload.paymentNote = payload.settings.paymentNote || payload.paymentNote || '';
      if (payload.settings.auditHistory) {
        payload.auditHistory = payload.settings.auditHistory;
      }
      delete payload.settings;
    }

    // Advanced Payload Validation
    const validationResult = validatePayload(invoiceSchema, payload);
    if (!validationResult.success && !isDemoSessionActive) {
      toast.error('Validation Error: Invalid invoice data.');
      console.error('Invoice Validation Failed:', validationResult.errors);
      return;
    }
    if (validationResult.success) {
      payload = validationResult.data;
    }

    // Final Integrity Check
    if (payload.items && payload.items.length > 0) {
      const hasValidItems = payload.items.some(i => (parseFloat(i.qty) || 0) > 0 && (parseFloat(i.rate) || 0) > 0);
      if (hasValidItems && (!payload.grandTotal || payload.grandTotal === 0)) {
        console.warn('⚠️ CRITICAL: Attempted to save invoice with ₹0 grand total but valid items exist. Forcing recalculation to prevent data corruption.');
        const recalculated = calculateTotals(payload.items, payload.taxPercentage || 0, payload.discountAmount || 0);
        payload.subtotal = recalculated.subtotal;
        payload.taxAmount = recalculated.taxAmount;
        payload.grandTotal = recalculated.grandTotal;
        payload.balanceDue = Math.max(0, recalculated.grandTotal - (payload.amountPaid || 0));
      }
    }

    const isNew = !payload.id || !targetInvoices.some(inv => inv.id === payload.id);
    if (isNew && revenueStatus.lockStatus === 'locked') {
      toast.error('New invoice creation is locked. Please clear your platform dues.');
      return;
    }
    const freeLimit = settings?.freeInvoiceLimit !== undefined ? settings.freeInvoiceLimit : 15;
    const isPPBActive = revenueStatus.lockStatus !== 'none' || revenueStatus.platformDueAmount > 0;
    if (isNew && subscription.status !== 'premium' && invoices.length >= freeLimit && !isSilent && !isPPBActive) {
      setShowPaywallModal(true);
      return;
    }
    let unlinkedItems = false;
    let lowStockWarning = false;

    let productsUpdated = false;
    const currentProducts = [...products];
    const updatedProductIds = new Set();

    // 1. If editing an existing invoice, reverse previous stock deduction
    const oldInvoice = payload.id ? targetInvoices.find(inv => inv.id === payload.id) : null;
    if (oldInvoice && oldInvoice.items) {
      for (const oldItem of oldInvoice.items) {
        const itemName = (oldItem.description || oldItem.productName || oldItem.serviceName || oldItem.itemService || '').trim().toLowerCase();
        if (!itemName) continue;

        const matchedProduct = currentProducts.find(p => p.name.trim().toLowerCase() === itemName);
        if (matchedProduct && matchedProduct.stockQty !== undefined) {
          const oldQty = parseFloat(oldItem.qty) || 1;
          matchedProduct.stockQty += oldQty;
          updatedProductIds.add(matchedProduct.id);
          productsUpdated = true;
        }
      }
    }

    // 2. Apply new stock deduction
    for (const item of payload.items) {
      const itemName = (item.description || item.productName || item.serviceName || item.itemService || '').trim().toLowerCase();
      if (!itemName) continue;

      const matchedProduct = currentProducts.find(p => p.name.trim().toLowerCase() === itemName);
      
      if (matchedProduct) {
        const requestedQty = parseFloat(item.qty) || 1;
        const currentStock = matchedProduct.stockQty !== undefined ? matchedProduct.stockQty : 0;
        if (currentStock < requestedQty) {
          lowStockWarning = true;
          matchedProduct.stockQty = 0; // Prevent going below 0 without confirmation
        } else {
          matchedProduct.stockQty = currentStock - requestedQty;
        }
        updatedProductIds.add(matchedProduct.id);
        productsUpdated = true;
      } else {
        unlinkedItems = true;
      }
    }

    if (productsUpdated) {
      const savePromises = [];
      for (const p of currentProducts) {
        if (updatedProductIds.has(p.id)) {
          savePromises.push(productEngine.saveProduct(p));
        }
      }
      Promise.all(savePromises).catch(e => console.error("Error saving products:", e));
      setProducts(currentProducts);
    }

    // --- Customer Linking Logic ---
    if (saveCustomerAsNew && payload.customerName && !isSilent) {
      // Check if customer already exists
      const existingCustomer = customers.find(c => 
        c.name.toLowerCase() === payload.customerName.toLowerCase() || 
        (payload.customerPhone && c.phone === payload.customerPhone)
      );
      
      if (existingCustomer) {
        payload.customerId = existingCustomer.id;
      } else {
        const newCustomer = {
          id: 'cust-' + Date.now(),
          name: payload.customerName,
          phone: payload.customerPhone || '',
          email: payload.customerEmail || '',
          address: payload.customerAddress || '',
        };
        handleSaveCustomer(newCustomer, true);
        payload.customerId = newCustomer.id;
      }
    } else if (!payload.customerId && payload.customerPhone) {
      // Fallback for missing customer ID if phone is provided
      const existingCustomer = customers.find(c => c.phone === payload.customerPhone || c.name === payload.customerName);
      if (existingCustomer) {
        payload.customerId = existingCustomer.id;
      }
    }

    // --- Save Logic ---
    if (isDemoSessionActive) {
      if (!payload.id) {
        payload.id = 'demo-inv-' + Date.now();
        if (!payload.invoiceNumber) payload.invoiceNumber = 'DEMO-INV-' + (1000 + demoInvoices.length);
        payload.createdAt = new Date().toISOString();
        payload.updatedAt = payload.createdAt;
      } else {
        payload.updatedAt = new Date().toISOString();
      }
      
      saveDemoInvoice(payload);
      
      if (!isSilent) {
        toast.success('Saved to Demo Session');
        setEditingInvoice(null);
        setCurrentTab('dashboard'); 
        
        // Trigger Confetti in Sandbox!
        if (subscription?.planStatus === 'premium' || (subscription?.planId && subscription.planId.toLowerCase() !== 'free')) {
          import('./utils/feedback').then(({ triggerPremiumConfetti }) => triggerPremiumConfetti()).catch(console.error);
        }
      }
      return payload;
    }

    try {
      const { updatedInvoices, firebaseStatus } = await invoiceEngine.saveInvoice(payload);
      setInvoices(updatedInvoices);

      if (!isSilent) {
        if (firebaseStatus === 'failed') {
          toast.success('Invoice created successfully. (Saved locally. Firebase sync pending.)');
        } else {
          toast.success('Invoice created successfully');
        }
        
        sendEmpireEvent({
          eventType: "invoice_created",
          message: "Invoice created in BillQyro",
          page: "create-invoice",
          metadata: { feature: "invoice", action: "created", privateDataIncluded: false }
        });

        // Trigger Premium Celebration Confetti
        if (subscription?.planStatus === 'premium' || (subscription?.planId && subscription.planId.toLowerCase() !== 'free')) {
          import('./utils/feedback').then(({ triggerPremiumConfetti }) => {
            triggerPremiumConfetti();
          }).catch(console.error);
        }

        // Trigger haptic & audio feedback
        if (payload.paymentStatus === 'Paid' && (!oldInvoice || oldInvoice.paymentStatus !== 'Paid')) {
          triggerPaymentSuccessFeedback();
          triggerVoiceFeedback("Payment received successfully!");
          window.dispatchEvent(new Event('trigger-confetti'));
        } else {
          triggerPopFeedback();
        }

        if (unlinkedItems) {
          toast.custom(
            (t) => (
              <div className={`${t.visible ? 'animate-enter' : 'animate-leave'} max-w-md w-full bg-theme-warning/5 dark:bg-amber-950/40 shadow-lg rounded-xl pointer-events-auto flex ring-1 ring-amber-500/30`}>
                <div className="flex-1 w-0 p-4">
                  <div className="flex items-start">
                    <div className="flex-shrink-0 pt-0.5">
                      <span className="text-xl">⚠️</span>
                    </div>
                    <div className="ml-3 flex-1">
                      <p className="text-sm font-semibold text-amber-800 dark:text-amber-300">
                        Some bill items are not linked to products, so inventory stock was not updated.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="flex border-l border-amber-500/20">
                  <button
                    onClick={() => {
                      toast.dismiss(t.id);
                      setCurrentTab('products');
                    }}
                    className="w-full border border-transparent rounded-none rounded-r-xl p-4 flex items-center justify-center text-xs font-bold text-amber-700 dark:text-amber-400 hover:bg-theme-warning/10 focus:outline-none transition-colors"
                  >
                    Link Products
                  </button>
                </div>
              </div>
            ),
            { duration: 6000 }
          );
        } else if (productsUpdated) {
          toast.success('Inventory stock updated successfully.', { duration: 4000 });
        }

        if (lowStockWarning) {
          toast.error('Low stock or insufficient stock for some products.', { duration: 4000 });
        }

        setEditingInvoice(null);
        setCurrentTab('invoices');
      }
      return payload;
    } catch (e) {
      console.error("Error saving invoice locally:", e);
      return null;
    }
  };

  const handleDeleteInvoice = async (id, permanent = false, skipConfirmation = false) => {
    if (isDemoSessionActive) {
      deleteDemoInvoice(id);
      toast.success('Deleted from Demo Session');
      return;
    }

    const executeDelete = async () => {
      triggerDeleteFeedback();
      const { updatedInvoices, firebaseStatus } = await invoiceEngine.deleteInvoice(id, permanent);
      setInvoices(updatedInvoices);
      if (firebaseStatus === 'failed') {
        toast.success(permanent ? 'Invoice permanently deleted locally. Will sync when online.' : 'Invoice moved to trash locally.');
      } else {
        toast.success(permanent ? 'Invoice permanently deleted!' : 'Invoice moved to trash.');
      }
    };

    if (permanent || skipConfirmation) {
      await executeDelete();
    } else {
      toast.custom(
        (t) => (
          <div className={`${t.visible ? 'animate-enter' : 'animate-leave'} max-w-sm w-full bg-theme-surface/90 backdrop-blur-xl shadow-[0_0_50px_rgba(244,63,94,0.15)] rounded-2xl pointer-events-auto border border-rose-500/20 overflow-hidden`}>
            <div className="p-6 flex flex-col items-center text-center">
              <div className="w-14 h-14 rounded-full bg-gradient-to-br from-rose-500/20 to-rose-500/5 text-rose-500 flex items-center justify-center mb-4 shadow-[0_0_15px_rgba(244,63,94,0.2)]">
                <Trash2 className="w-7 h-7" />
              </div>
              <h3 className="text-xl font-black text-theme-primary mb-2">Move to Trash?</h3>
              <p className="text-sm text-theme-muted font-bold mb-6">
                Are you sure you want to move this invoice to the trash? You can restore it later if needed.
              </p>
              <div className="flex w-full gap-3">
                <button
                  onClick={() => toast.dismiss(t.id)}
                  className="flex-1 bg-theme-app border border-theme-border-soft text-theme-primary font-bold py-3 rounded-xl transition-all hover:bg-theme-border-soft hover:shadow-md"
                >
                  Cancel
                </button>
                <button
                  onClick={async () => {
                    toast.dismiss(t.id);
                    await executeDelete();
                  }}
                  className="flex-1 bg-gradient-to-r from-rose-500 to-rose-600 text-white font-black py-3 rounded-xl transition-all hover:from-rose-600 hover:to-rose-700 shadow-lg shadow-rose-500/25"
                >
                  Yes, Delete
                </button>
              </div>
            </div>
          </div>
        ),
        { duration: 4000 }
      );
    }
  };

  // Customers
  const handleSaveCustomer = async (payload) => {
    // Validate Customer Payload
    const validationResult = validatePayload(customerSchema, payload);
    if (!validationResult.success) {
      toast.error('Validation Error: Invalid customer data.');
      console.error('Customer Validation Failed:', validationResult.errors);
      return;
    }
    const validatedCust = validationResult.data;

    if (isDemoSessionActive) {
      if (!validatedCust.id) {
        validatedCust.id = 'demo-cust-' + Date.now();
      }
      saveDemoCustomer(validatedCust);
      toast.success('Saved to Demo Session');
      return;
    }
    try {
      const { updatedCustomers, firebaseStatus } = await customerEngine.saveCustomer(validatedCust);
      setCustomers(updatedCustomers);
      if (firebaseStatus === 'failed') {
        toast.success('Customer saved locally. Will sync with cloud when online.');
      } else {
        toast.success('Customer saved successfully');
      }
      sendEmpireEvent({
        eventType: "customer_added",
        message: "Customer saved",
        page: "customers",
        metadata: { feature: "customer", action: "added", privateDataIncluded: false }
      });
    } catch (error) {
      console.error(error);
      toast.error('Failed to save customer');
    }
  };

  const handleDeleteCustomer = async (id) => {
    if (isDemoSessionActive) {
      const customers = getDemoCustomers().filter(i => i.id !== id);
      localStorage.setItem('billqyro_demo_customers', JSON.stringify(customers));
      toast.success('Deleted from Demo Session');
      window.dispatchEvent(new Event('storage'));
      return;
    }
    if (window.confirm('Are you sure you want to delete this customer?')) {
      const { updatedCustomers, firebaseStatus } = await customerEngine.deleteCustomer(id);
      setCustomers(updatedCustomers);
      if (firebaseStatus === 'failed') {
        toast.success('Customer deleted locally. Will sync with cloud when online.');
      } else {
        toast.success('Customer deleted');
      }
    }
  };

  // Products
  const handleSaveProduct = async (payload) => {
    if (isDemoSessionActive) {
      if (!payload.id) {
        payload.id = 'demo-prod-' + Date.now();
      }
      saveDemoProduct(payload);
      toast.success('Saved to Demo Session');
      return;
    }
    try {
      const { updatedProducts, firebaseStatus } = await productEngine.saveProduct(payload);
      setProducts(updatedProducts);
      if (firebaseStatus === 'failed') {
        toast.success('Product/Service saved locally. Will sync with cloud when online.');
      } else {
        toast.success('Product/Service saved successfully');
      }
      sendEmpireEvent({
        eventType: "product_added",
        message: "Product saved",
        page: "products",
        metadata: { feature: "product", action: "added", privateDataIncluded: false }
      });
    } catch (error) {
      console.error(error);
      toast.error('Failed to save product');
    }
  };

  const handleDeleteProduct = async (id) => {
    if (isDemoSessionActive) {
      const products = getDemoProducts().filter(i => i.id !== id);
      localStorage.setItem('billqyro_demo_products', JSON.stringify(products));
      toast.success('Deleted from Demo Session');
      window.dispatchEvent(new Event('storage'));
      return;
    }
    const { updatedProducts, firebaseStatus } = await productEngine.deleteProduct(id);
    setProducts(updatedProducts);
    if (firebaseStatus === 'failed') {
      toast.success('Product deleted locally. Will sync with cloud when online.', { id: 'delete-product-toast' });
    }
  };

  // Students
  const handleSaveStudent = async (payload) => {
    if (isDemoSessionActive) {
      if (!payload.id) payload.id = 'demo-stu-' + Date.now();
      const list = JSON.parse(localStorage.getItem('billqyro_demo_students') || '[]');
      const idx = list.findIndex(s => s.id === payload.id);
      if (idx >= 0) list[idx] = payload; else list.push(payload);
      localStorage.setItem('billqyro_demo_students', JSON.stringify(list));
      toast.success('Saved to Demo Session');
      return;
    }
    try {
      const { updatedStudents, firebaseStatus } = await customerEngine.saveCustomer(payload);
      setStudents(updatedStudents);
      if (firebaseStatus === 'failed') toast.success('Student saved locally. Will sync when online.');
      else toast.success('Student saved successfully');
    } catch (error) {
      console.error(error);
      toast.error('Failed to save student');
    }
  };

  const handleDeleteStudent = async (id) => {
    if (isDemoSessionActive) {
      const list = JSON.parse(localStorage.getItem('billqyro_demo_students') || '[]').filter(s => s.id !== id);
      localStorage.setItem('billqyro_demo_students', JSON.stringify(list));
      toast.success('Deleted from Demo Session');
      window.dispatchEvent(new Event('storage'));
      return;
    }
    const { updatedStudents, firebaseStatus } = await customerEngine.deleteCustomer(id);
    setStudents(updatedStudents);
    if (firebaseStatus === 'failed') {
      toast.success('Student deleted locally. Will sync with cloud when online.', { id: 'delete-student-toast' });
    }
  };

  // Expenses
  const handleSaveExpense = async (payload) => {
    try {
      const { updatedExpenses, firebaseStatus } = await expenseEngine.saveExpense(payload);
      setExpenses(updatedExpenses);
      if (firebaseStatus === 'failed') {
        toast.success('Expense saved locally. Will sync with cloud when online.');
      } else {
        toast.success('Expense saved successfully');
      }
    } catch (error) {
      console.error(error);
      toast.error('Failed to save expense');
    }
  };

  const handleDeleteExpense = async (id) => {
    const { updatedExpenses, firebaseStatus } = await expenseEngine.deleteExpense(id);
    setExpenses(updatedExpenses);
    if (firebaseStatus === 'failed') {
      toast.success('Expense deleted locally. Will sync with cloud when online.', { id: 'delete-expense-toast' });
    }
  };


  // Settings
  const handleSaveSettings = async (payload) => {
    if (isDemoSessionActive) {
      localStorage.setItem('billqyro_demo_settings', JSON.stringify(payload));
      toast.success('Settings saved to Demo Session');
      window.dispatchEvent(new Event('storage'));
      return true;
    }
    try {
      const updatedSettings = await settingsEngine.saveSettings(payload);
      setSettings(updatedSettings);
      window.dispatchEvent(new CustomEvent('billqyro:settings-updated', { detail: updatedSettings }));
      toast.success('Settings saved successfully');
      sendEmpireEvent({
        eventType: "settings_updated",
        message: "App settings updated",
        page: "settings",
        metadata: { privateDataIncluded: false }
      });
      return true;
    } catch (error) {
      console.error(error);
      toast.error('Failed to save settings');
      throw error;
    }
  };

  // Reset System Data
  const handleResetDemo = () => {
    const freshData = adminEngine.factoryResetAllData();
    setSettings(freshData.settings);
    setCustomers(freshData.customers);
    setProducts(freshData.products);
    setInvoices(freshData.invoices);
    setExpenses(freshData.expenses);
    setSubscription(freshData.subscription);
    toast.success('Demo data has been reset!');
    setCurrentTab('dashboard');
  };

  // Import Backup Data and Sync React States
  const handleImportBackup = (parsedData) => {
    backupEngine.importRestore(parsedData);
    setSettings(parsedData.settings);
    setCustomers(parsedData.customers);
    setProducts(parsedData.products);
    setInvoices(parsedData.invoices);
    setExpenses(parsedData.expenses);
    setSubscription(parsedData.subscription);
    setCurrentTab('dashboard');
  };

  // --- PDF GENERATOR WORKER ---
  const handleDownloadPDF = (invoice) => {
    if (!settings || !settings.businessName) {
      toast.error('⚠️ Business settings are incomplete. Please complete your business settings first.');
      setCurrentTab('settings');
      return;
    }
    const isPremium = subscription.status === 'premium';
    downloadInvoicePDF(invoice, settings, isPremium)
      .then((ok) => {
        if (ok) {
          sendEmpireEvent({
            eventType: "pdf_downloaded",
            message: "Invoice PDF generated",
            page: "invoice",
            metadata: { feature: "pdf", action: "downloaded", privateDataIncluded: false }
          });
        }
      })
      .catch((err) => {
        sendEmpireError({
          errorType: "pdf_failed",
          message: err?.toString() || "PDF generation failed",
          severity: "Medium",
          page: "invoice"
        });
        toast.error(`PDF Error: ${err?.toString() || "Unknown error generating PDF"}`);
      });
  };

  // --- IMAGE GENERATOR WORKER ---
  const handleDownloadImage = (invoice) => {
    if (!settings || !settings.businessName) {
      toast.error('⚠️ Business settings are incomplete. Please complete your business settings first.');
      setCurrentTab('settings');
      return;
    }
    downloadInvoiceImage(invoice, settings)
      .then((ok) => {
        if (ok) {
          sendEmpireEvent({
            eventType: "image_downloaded",
            message: "Invoice image generated",
            page: "invoice",
            metadata: { feature: "image", action: "downloaded", privateDataIncluded: false }
          });
        }
      })
      .catch((err) => {
        sendEmpireError({
          errorType: "image_failed",
          message: err?.toString() || "Image generation failed",
          severity: "Medium",
          page: "invoice"
        });
        toast.error(`Image Error: ${err?.toString() || "Unknown error generating image"}`);
      });
  };

  // HARD DEMO MODE ISOLATION SWITCH
  const activeInvoices = isDemoSessionActive ? demoInvoices : invoices;
  const activeCustomers = isDemoSessionActive ? demoCustomers : customers;
  const activeStaffs = isDemoSessionActive ? demoStaffs : staffs;
  const activeProducts = isDemoSessionActive ? demoProducts : products;
  const activeExpenses = isDemoSessionActive ? demoExpenses : expenses;
  
  let activeSettings = (isDemoSessionActive && demoSettings) ? demoSettings : settings;
  if (isDemoSessionActive && isVideoCreatorMode && activeSettings) {
    activeSettings = {
      ...activeSettings,
      businessName: activeSettings.businessName || 'Demo Corp',
      ownerName: 'Demo Owner',
      email: 'hello@democorp.local',
      phone: '+1 555-0199',
      logoUrl: '',
      whatsapp: '+1 555-0199'
    };
  }

  // --- TAB ROUTER SWITCHBOARD ---
  const TAB_TO_FEATURE_MAP = {
    'invoices': 'invoice', 'create-invoice': 'invoice', 'estimates': 'invoice',
    'customers': 'customer', 'patients': 'customer', 'students': 'customer', 'clients': 'customer',
    'due-ledger': 'treasury', 'pending-payments': 'payment', 'reports': 'reports',
    'expenses': 'treasury.moneyOut', 'products': 'product', 'orders': 'product', 'bank': 'bank',
    'appointments': 'customer', 'delivery': 'product', 'measurements': 'product',
    'designBook': 'product', 'devices': 'product', 'serviceJobs': 'product', 'projects': 'product'
  };

  const renderTabContent = (targetTab = currentTab) => {
    const isMaintenanceMode = (globalMaintenanceMode || activeSettings?.maintenanceMode) && !adminEngine.isAdminUser(authEngine.getAuthSession());

    // Feature gating fallback
    if (!featuresLoading) {
      const requiredFeature = TAB_TO_FEATURE_MAP[targetTab];
      if (requiredFeature && !isFeatureEnabled(requiredFeature)) {
        return (
          <div className="flex flex-col items-center justify-center h-full text-center p-10 bg-theme-main">
            <Lock className="w-16 h-16 text-theme-muted mb-4" />
            <h2 className="text-2xl font-black text-white mb-2">Feature Disabled</h2>
            <p className="text-theme-muted max-w-md mb-6">
              The '{targetTab}' module is currently disabled for this workspace. You can enable it from the Settings Studio.
            </p>
            <button onClick={() => setCurrentTab('dashboard')} className="px-6 py-2.5 bg-theme-accent text-white font-bold rounded-xl hover:bg-theme-accent/80 transition-colors">
              Return to Dashboard
            </button>
          </div>
        );
      }
    }

    switch (targetTab) {
      case 'landing':
        if (isAuthenticated) {
          setTimeout(() => setCurrentTab('dashboard'), 0);
          return <div className="flex flex-col items-center justify-center h-full text-center p-10"><ClassicLoader /></div>;
        }
        return <Landing onLoginSuccess={handleLoginSuccess} />;
      case 'cyber-dashboard':
        return <CyberDashboard setCurrentTab={setCurrentTab} />;
      case 'portal-hub':
        return <PortalHub />;
      case 'quick-tools':
        return <QuickToolsCenter />;
      case 'customer-register':
        return <CustomerRegister />;
      case 'cash-management':
        return <CashManagement />;
      case 'dashboard':
        return (
          <Dashboard
            invoices={activeInvoices}
            customers={activeCustomers}
            staffs={activeStaffs}
            products={activeProducts}
            expenses={activeExpenses}
            onViewInvoice={(inv) => {
              setEditingInvoice(inv);
              setCurrentTab('invoices');
            }}
            onEditInvoice={(inv) => {
              setEditingInvoice(inv);
              setCurrentTab('create-invoice');
            }}
            onDeleteInvoice={handleDeleteInvoice}
            onDownloadPDF={handleDownloadPDF}
            setCurrentTab={setCurrentTab}
            businessSettings={activeSettings}
            installPromptEvent={installPromptEvent}
            isAppInstalled={isAppInstalled}
            onInstallApp={handleInstallApp}
            subscription={subscription}
            onQuickBillOpen={() => setIsQuickBillOpen(true)}
            pendingPaymentsCount={pendingPayments.length}
            isLoading={isDataHydrating}
            revenueStatus={revenueStatus}
            onSaveCustomer={handleSaveCustomer}
            permissions={userPermissions}
            workspaceVerified={workspaceVerified}
          />
        );
      case 'pending-payments':
        return (
          <PendingPayments 
            setCurrentTab={setCurrentTab}
            pendingPayments={pendingPayments}
          />
        );
      case 'help-center':
        return (
          <HelpCenter />
        );
      case 'customer-portal-config':
        return <CustomerPortalConfig />;
      case 'system-health':
        return <SystemHealth setCurrentTab={setCurrentTab} />;
      case 'sandbox-admin':
        return <SandboxAdmin setCurrentTab={setCurrentTab} />;
      case 'audit-logs':
        return (
          <AuditLogs setCurrentTab={setCurrentTab} />
        );
      case 'due':
      case 'due-ledger':
        return (
          <DueLedger 
            customers={activeCustomers}
            staffs={activeStaffs} 
            invoices={activeInvoices} 
            businessSettings={activeSettings}
          />
        );
      case 'bank':
        return (
          <InternalBank
            customers={activeCustomers}
            staffs={activeStaffs}
            invoices={activeInvoices}
            businessSettings={activeSettings}
          />
        );
      case 'reports':
        return (
          <Reports 
            invoices={activeInvoices} 
            customers={activeCustomers}
            staffs={activeStaffs} 
            businessSettings={activeSettings}
          />
        );
      case 'invoices':
        return (
          <Invoices
            invoices={activeInvoices}
            editingInvoice={editingInvoice}
            onEditInvoice={setEditingInvoice}
            onDeleteInvoice={handleDeleteInvoice}
            onDownloadPDF={handleDownloadPDF}
            onDownloadImage={handleDownloadImage}
            setCurrentTab={setCurrentTab}
            businessSettings={activeSettings}
          />
        );
      case 'estimates':
        return (
          <Estimates
            invoices={activeInvoices}
            editingInvoice={editingInvoice}
            onEditInvoice={setEditingInvoice}
            onDeleteInvoice={handleDeleteInvoice}
            onDownloadPDF={handleDownloadPDF}
            onDownloadImage={handleDownloadImage}
            setCurrentTab={setCurrentTab}
            businessSettings={activeSettings}
            onSaveInvoice={handleSaveInvoice}
          />
        );
      case 'create-invoice':
        if ((isMaintenanceMode || (activeSettings?.disableNewBillCreation && !adminEngine.isAdminUser(authEngine.getAuthSession()))) && !editingInvoice) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">New Bill Creation Disabled</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                The platform is currently undergoing scheduled maintenance or the owner has disabled new bill creation. You can still view existing bills and run backups.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Go to Dashboard
              </button>
            </div>
          );
        }
        if (revenueStatus.lockStatus === 'locked' && !editingInvoice) {
          return (
            <React.Suspense fallback={<div className="flex h-screen items-center justify-center"><ClassicLoader /></div>}>
              <PaymentDueScreen 
                pendingAmount={revenueStatus.platformPendingAmount}
                chargeableBills={revenueStatus.billableBillsCount}
                onCancel={() => setCurrentTab('dashboard')}
                onLogout={() => {
                  authEngine.logout();
                  setIsAuthenticated(false);
                  setCurrentTab('login');
                }}
              />
            </React.Suspense>
          );
        }
        return (
          <CreateInvoice
            invoices={activeInvoices}
            customers={activeCustomers}
            staffs={activeStaffs}
            products={activeProducts}
            businessSettings={activeSettings}
            onSaveInvoice={handleSaveInvoice}
            setCurrentTab={setCurrentTab}
            editingInvoice={editingInvoice}
            onDownloadPDF={handleDownloadPDF}
            onBack={() => {
              setEditingInvoice(null);
              setCurrentTab('dashboard');
            }}
            onQuickBillOpen={() => setIsQuickBillOpen(true)}
            subscription={subscription}
          />
        );
      case 'guide':
        // Legacy fallback
        return (
          <HelpCenter />
        );
      case 'customers':
        return (
          <Customers
            customers={activeCustomers}
            staffs={activeStaffs}
            invoices={activeInvoices}
            onSaveCustomer={handleSaveCustomer}
            onDeleteCustomer={handleDeleteCustomer}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
            onCreateBill={(cust) => {
              setEditingInvoice({ customerName: cust.name });
              setCurrentTab('create-invoice');
            }}
          />
        );
      case 'products':
        return (
          <Products
            products={activeProducts}
            onSaveProduct={handleSaveProduct}
            onDeleteProduct={handleDeleteProduct}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'expenses':
        return (
          <Expenses
            expenses={activeExpenses}
            onSaveExpense={handleSaveExpense}
            onDeleteExpense={handleDeleteExpense}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'appointments':
        return <Appointments />;
      case 'orders':
        return (
          <Orders
            invoices={activeInvoices}
            customers={activeCustomers}
            staffs={activeStaffs}
            businessSettings={activeSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'patients':
        return <Patients />;
      case 'students':
        if (activeSettings && !isEducationBusiness(activeSettings.defaultBillingTemplate)) {
          // If a Business workspace attempts to open /students, automatically redirect
          // We don't render Students, we redirect to customers
          setTimeout(() => setCurrentTab('customers'), 0);
          return <div className="min-h-screen flex items-center justify-center"><ClassicLoader /></div>;
        }
        return <Students students={students} onSaveStudent={handleSaveStudent} onDeleteStudent={handleDeleteStudent} />;
      case 'clients':
        return <Clients />;
      case 'measurements':
        return <Measurements />;
      case 'designBook':
        return <DesignBook />;
      case 'devices':
        return <Devices />;
      case 'serviceJobs':
        return <ServiceJobs />;
      case 'projects':
        return <Projects />;
      case 'delivery':
        return <Delivery />;
      case 'premium-upgrade':
        if (isMaintenanceMode || activeSettings?.disablePremiumUpgrade) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">Premium Upgrades Suspended</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                Upgrading to premium features is temporarily suspended by the administrator.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Back to Dashboard
              </button>
            </div>
          );
        }
        return (
          <StudioLayout 
            settings={activeSettings} 
            onSaveSettings={handleSaveSettings} 
            setCurrentTab={setCurrentTab}
            subscription={subscription}
          />
        );
      case 'subscription':
        return (
          <StudioLayout 
            settings={activeSettings} 
            onSaveSettings={handleSaveSettings} 
            setCurrentTab={setCurrentTab}
            subscription={subscription}
          />
        );

      case 'pdf-templates':
        if (isMaintenanceMode || activeSettings?.disableLiveLinkCreation) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">Customization Suspended</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                Template customization is temporarily suspended by the administrator.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Back to Dashboard
              </button>
            </div>
          );
        }
        return (
          <PdfTemplateStudio 
            businessSettings={settings} 
            setSettings={setSettings} 
            setCurrentTab={setCurrentTab}
            subscription={subscription}
          />
        );
      case 'live-link-templates':
      case 'billing-portal-settings':
      case 'student-portal-settings':
        if (isMaintenanceMode || activeSettings?.disableLiveLinkCreation) {
          return (
            <div className="flex-1 flex flex-col items-center justify-center p-6 text-center">
              <div className="w-16 h-16 bg-theme-warning/20 text-theme-warning rounded-2xl flex items-center justify-center mx-auto mb-6">
                <AlertTriangle className="w-8 h-8 text-theme-warning" />
              </div>
              <h2 className="text-xl font-bold text-white mb-2">Live Invoice Links Suspended</h2>
              <p className="text-sm text-theme-muted max-w-sm mb-6">
                Live link customization and settings are temporarily suspended by the administrator.
              </p>
              <button onClick={() => setCurrentTab('dashboard')} className="px-5 py-2.5 bg-theme-accent text-white font-bold rounded-xl">
                Back to Dashboard
              </button>
            </div>
          );
        }
        return (
          <LiveLinkTemplateStudio 
            settings={settings}
            onSaveSettings={handleSaveSettings}
            subscription={subscription}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'marketplace':
        return (
          <TemplateMarketplace
            settings={settings}
            onSaveSettings={handleSaveSettings}
            subscription={subscription}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'design-studio':
        return (
          <DesignStudio setCurrentTab={setCurrentTab} />
        );
      case 'backup-restore':
        return (
          <BackupRestore
            settings={settings}
            invoices={invoices}
            customers={customers}
            products={products}
            expenses={expenses}
            onImportBackup={handleImportBackup}
          />
        );
      case 'more':
        return (
          <MoreMenu
            setCurrentTab={setCurrentTab}
            isAuthenticated={isAuthenticated}
            onLoginSuccess={handleLoginSuccess}
            businessSettings={settings}
            userRole={userRole}
            pendingPaymentsCount={pendingPayments.length}
          />
        );
      case 'privacy':
        return <PrivacyPolicy setCurrentTab={setCurrentTab} />;
      case 'terms':
        return <TermsOfService setCurrentTab={setCurrentTab} />;
      case 'refund':
        return <RefundPolicy setCurrentTab={setCurrentTab} />;
      case 'data-deletion':
        return <DataDeletion onBack={() => setCurrentTab('more')} />;
      case 'support':
        return <Support onBack={() => setCurrentTab('more')} />;
      case 'workspace-manager':
        return (
          <WorkspaceManager
            businessWorkspaces={businessWorkspaces}
            activeWorkspaceId={activeWorkspaceId}
            setActiveWorkspace={setActiveWorkspace}
            settings={activeSettings}
            onSaveSettings={handleSaveSettings}
            setCurrentTab={setCurrentTab}
          />
        );
      case 'settings': {
        const session = authEngine.getAuthSession();
        return (
          <StudioLayout
            settings={activeSettings}
            onSaveSettings={handleSaveSettings}
            isAdmin={adminEngine.isAdminUser(session)}
            onResetDemo={handleResetDemo}
            onImportBackup={handleImportBackup}
            invoices={activeInvoices}
            customers={activeCustomers}
            staffs={activeStaffs}
            installPromptEvent={installPromptEvent}
            isAppInstalled={isAppInstalled}
            onInstallApp={handleInstallApp}
            subscription={subscription}
            setCurrentTab={setCurrentTab}
          />
        );
      }
      default:
        // Automatically recover from invalid tabs stored in localStorage
        setTimeout(() => setCurrentTab('dashboard'), 0);
        return (
          <div className="flex flex-col items-center justify-center h-full text-center p-10">
            <ClassicLoader />
            <p className="text-theme-muted font-bold mt-4 animate-pulse">Recovering workspace...</p>
          </div>
        );
    }
  };

  // Intercept for Public Invoice Loading/Display (No Auth Route Interceptor)
  if (loadingPublicInvoice) {
    return (
      <div className="min-h-screen bg-theme-main flex flex-col items-center justify-center p-6 text-center text-white font-sans">
        <ClassicLoader />
        <p className="text-theme-muted text-xs font-bold uppercase mt-4 tracking-widest animate-pulse">Loading secure digital invoice...</p>
      </div>
    );
  }

  if (publicToken) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <PublicInvoice initialInvoice={publicInvoice} />
      </React.Suspense>
    );
  }

  if (portalId) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <CustomerWorkspace customerId={portalId === 'verification-pending' ? null : portalId} />
      </React.Suspense>
    );
  }

  if (eduPortalId) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <StudentPortal studentId={eduPortalId} />
      </React.Suspense>
    );
  }

  // Show onboarding/login if not authenticated
  const isDemoJourneyActive = localStorage.getItem('billqyro_demo_journey_mode') === 'true';
  const isDemoLoggedIn = localStorage.getItem('billqyro_demo_logged_in') === 'true';

  if (isDemoSessionActive && isDemoJourneyActive && !isDemoLoggedIn) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <DemoLogin onDemoLoginSuccess={() => {
          setIsAuthenticated(true);
          setShowWelcomeAnimation(true);
          window.dispatchEvent(new Event('storage'));
        }} />
      </React.Suspense>
    );
  }

  if (!isAuthenticated && (!isDemoSessionActive || !isDemoJourneyActive)) {
    return (
      <React.Suspense fallback={
        <div className="flex h-screen items-center justify-center">
          <ClassicLoader />
        </div>
      }>
        <Landing onLoginSuccess={handleLoginSuccess} />
      </React.Suspense>
    );
  }

  // --- Account Blocked Interceptor ---
  if (settings?.blocked === true) {
    const session = authEngine.getAuthSession();
    if (!adminEngine.isAdminUser(session)) {
      return (
        <div className="min-h-screen bg-theme-main flex flex-col items-center justify-center p-6 text-center font-sans text-white">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="max-w-md bg-theme-card p-8 rounded-3xl border border-theme-border-soft shadow-2xl space-y-6"
          >
            <div className="w-16 h-16 bg-theme-danger/20 text-theme-danger rounded-2xl flex items-center justify-center mx-auto shadow-lg shadow-rose-500/10">
              <Lock className="w-8 h-8" />
            </div>
            <h1 className="text-2xl font-black tracking-tight text-white">Account Deactivated</h1>
            <p className="text-theme-muted text-xs font-semibold leading-relaxed">
              Your BillQyro workspace has been temporarily blocked by the platform administrator due to policy guidelines or outstanding billing concerns.
            </p>
            <div className="p-4 bg-theme-surface/50 rounded-2xl border border-theme-border-soft/80 text-left space-y-2">
              <span className="text-[10px] text-theme-muted uppercase font-black block tracking-widest">Administrator Notice</span>
              <p className="text-[11px] text-theme-muted font-semibold leading-relaxed">
                If you believe this is an error or wish to request immediate reactivation, please contact support at <strong className="text-theme-accent select-all">{settings.email || 'support@billqyro.com'}</strong> or email your account manager directly.
              </p>
            </div>
            <button
              onClick={() => {
                authEngine.logout();
                setIsAuthenticated(false);
              }}
              className="w-full py-3 bg-theme-card hover:bg-theme-surface text-white font-bold text-xs rounded-xl shadow-lg active:scale-[0.98] transition-all cursor-pointer uppercase tracking-wider"
            >
              Sign Out of Account
            </button>
          </motion.div>
        </div>
      );
    }
  }

  // --- Account Soft Lock Interceptor (Due Limit) ---
  const freeLimit = settings?.freeInvoiceLimit || 15;
  const pendingAmountLimit = settings?.maximumPendingDue || 100;
  const chargePerBill = settings?.chargePerBill || 5;
  
  if (subscription?.status !== 'premium' && invoices.length > freeLimit) {
    const chargeableBills = invoices.length - freeLimit;
    const pendingAmount = chargeableBills * chargePerBill;
    
    if (pendingAmount >= pendingAmountLimit) {
      const session = authEngine.getAuthSession();
      if (!adminEngine.isAdminUser(session)) {
        return (
          <React.Suspense fallback={<div className="flex h-screen items-center justify-center"><ClassicLoader /></div>}>
            <PaymentDueScreen 
              pendingAmount={pendingAmount} 
              chargeableBills={chargeableBills}
              onLogout={() => {
                authEngine.logout();
                setIsAuthenticated(false);
              }} 
            />
          </React.Suspense>
        );
      }
    }
  }

  // Root level maintenance mode interceptor removed to allow access to dashboard, invoices view, and backups.
  // Wait, the owner requested global maintenance block for NON-admins!
  const isMaintenanceMode = localStorage.getItem('billqyro_global_maintenance') === 'true';
  const isAdminSession = adminEngine.isAdminUser(authEngine.getAuthSession()) || localStorage.getItem('billqyro_admin_unlocked') === 'true';

  if (isMaintenanceMode && !isAdminSession) {
    return (
      <div className="h-screen w-full bg-theme-main flex flex-col items-center justify-center p-8 text-center relative overflow-hidden">
        <div className="absolute inset-0 bg-theme-danger/5 pointer-events-none" />
        <div className="p-4 rounded-full bg-theme-danger/20 mb-6">
          <ServerCrash className="w-12 h-12 text-theme-danger" />
        </div>
        <h1 className="text-4xl font-black text-theme-primary mb-4 tracking-tight">System Under Maintenance</h1>
        <p className="text-theme-secondary mb-8 max-w-md mx-auto">
          We are currently upgrading our servers to bring you a better experience. Please check back shortly.
        </p>
      </div>
    );
  }

  const path = window.location.pathname;
  const showAdminRoute = path === '/km-admin' || currentTab === 'admin-panel';

  // Enterprise Route Gate - Wait for Auth, Workspace, and Sync to resolve
  const isAppReady = !isAppBooting && (!isAuthenticated || (cloudSyncDone && settings));
  const isSetupIncomplete = isAuthenticated && activeSettings && !activeSettings.setupCompleted && !activeSettings.businessName;

  // Resolve currentTab when we reach layout (defaulting to dashboard if null)
  const resolvedTab = currentTab || 'dashboard';

  return (
    <ErrorBoundary>
      <AnimatePresence mode="wait">
        {!isAppReady ? (
          <motion.div 
            key="global-loader"
            exit={{ opacity: 0, transition: { duration: 0.25, ease: 'easeOut' } }}
            className="fixed inset-0 z-[9999] bg-theme-main flex flex-col items-center justify-center font-sans"
          >
            <ClassicLoader />
            <p className="text-theme-muted font-bold mt-4 animate-pulse">Loading workspace...</p>
          </motion.div>
        ) : showAdminRoute ? (
          <motion.div key="admin-route" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="w-full h-full">
            <React.Suspense fallback={<div className="flex h-screen items-center justify-center"><ClassicLoader /></div>}>
              <AdminRouteGuard setCurrentTab={(tab) => {
                setCurrentTab(tab);
                if (window.location.pathname === '/km-admin') {
                  window.history.replaceState({}, '', '/');
                }
              }}>
                <AdminPanel 
                  currentTab={resolvedTab} 
                  setCurrentTab={(tab) => {
                    setCurrentTab(tab);
                    if (window.location.pathname === '/km-admin') {
                      window.history.replaceState({}, '', '/');
                    }
                  }} 
                />
              </AdminRouteGuard>
            </React.Suspense>
          </motion.div>
        ) : (
          <motion.div key="main-app" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.2 }} className="w-full h-full flex flex-col">
            {isDemoSessionActive && (
              <div className="bg-amber-500 text-amber-950 px-4 py-2 flex items-center justify-between font-bold text-sm z-[999999] relative shadow-md">
                <span className="flex items-center">
                  <AlertTriangle className="w-4 h-4 mr-2"/> DEMO MODE ACTIVE — Real data is safe. {isVideoCreatorMode && " | Video Creator Masking ON"}
                </span>
                <button onClick={() => {
                  if (window.confirm("Exit Demo Mode and return to Owner Test Lab?")) {
                    if (window.confirm("Do you want to clear the Demo Sandbox data as well?")) {
                      localStorage.removeItem('billqyro_demo_customers');
                      localStorage.removeItem('billqyro_demo_invoices');
                      localStorage.removeItem('billqyro_demo_products');
                      localStorage.removeItem('billqyro_demo_reports');
                      localStorage.removeItem('billqyro_demo_payments');
                      localStorage.removeItem('billqyro_demo_settings');
                      localStorage.removeItem('billqyro_demo_logged_in');
                    }
                    localStorage.removeItem('billqyro_demo_session_active');
                    localStorage.removeItem('billqyro_demo_journey_mode');
                    localStorage.removeItem('billqyro_demo_video_creator');
                    window.location.href = '/km-admin';
                  }
                }} className="bg-amber-950 hover:bg-amber-900 text-amber-500 px-3 py-1 rounded-md text-xs transition-colors">Exit Demo</button>
              </div>
            )}
            <PostLoginWelcome 
              show={showWelcomeAnimation} 
              userName={settings?.businessName || ''} 
              onComplete={() => setShowWelcomeAnimation(false)} 
            />
            {isSetupIncomplete ? (
              <OnboardingWizard 
                onComplete={() => setCurrentTab('dashboard')} 
                businessSettings={activeSettings} 
                onSaveSettings={(newSettings) => {
                  settingsEngine.saveSettings(newSettings);
                  setSettings(newSettings);
                  if (isDemoSessionActive) {
                    setDemoSettings(newSettings);
                  }
                  setCurrentTab('dashboard');
                }}
                setCurrentTab={setCurrentTab}
              />
            ) : (
              <Layout
                currentTab={resolvedTab}
                setCurrentTab={(tab) => {
                  if (tab !== 'create-invoice') {
                    setEditingInvoice(null);
                  }
                  setCurrentTab(tab);
                }}
                onLogout={handleLogout}
                businessSettings={activeSettings}
                isAuthenticated={isAuthenticated}
                userRole={userRole}
                invoices={activeInvoices}
                subscription={subscription}
                userEmail={authEngine.getAuthSession()?.userEmail}
                onQuickBillOpen={() => setIsQuickBillOpen(true)}
                pendingPaymentsCount={pendingPayments.length}
                businessWorkspaces={businessWorkspaces}
                activeWorkspaceId={activeWorkspaceId}
                setActiveWorkspace={setActiveWorkspace}
                syncSource={isDemoSessionActive ? "local" : "cloud"}
                syncStatus={isDemoSessionActive ? "Local Sandbox" : syncStatus}
              >
                <AnimatePresence mode="wait">
                  <motion.div
                    key={resolvedTab}
                    variants={pageVariants}
                    initial="initial"
                    animate="animate"
                    exit="exit"
                    className="w-full h-full flex flex-col"
                  >
                    <React.Suspense fallback={
                      <div className="flex flex-1 min-h-[calc(100vh-250px)] items-center justify-center">
                        <ClassicLoader text="Loading..." />
                      </div>
                    }>
                      {renderTabContent(resolvedTab)}
                    </React.Suspense>
                  </motion.div>
                </AnimatePresence>
                
                <QuickBillModal 
                  isOpen={isQuickBillOpen}
                  onClose={() => setIsQuickBillOpen(false)}
                  onSave={handleSaveInvoice}
                  businessSettings={settings}
                  invoices={invoices}
                />
              </Layout>
            )}
            <Toaster
              position="bottom-center"
              toastOptions={{
                className: 'text-sm font-bold toast-above-nav',
                style: { borderRadius: '12px', background: '#fff', color: '#1e293b', marginBottom: 'calc(72px + env(safe-area-inset-bottom))' },
                success: { duration: 3000 },
                error: { duration: 4000 },
              }}
            />
            {/* Sync Badge moved to Layout Header */}
            
            {/* Paywall Modal */}
            <AnimatePresence>
              {showPaywallModal && (
                <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4">
                  <motion.div 
                    initial={{ opacity: 0 }} 
                    animate={{ opacity: 1 }} 
                    exit={{ opacity: 0 }} 
                    className="absolute inset-0 bg-black/60 backdrop-blur-sm"
                    onClick={() => setShowPaywallModal(false)}
                  />
                  <motion.div
                    initial={{ scale: 0.95, opacity: 0, y: 20 }}
                    animate={{ scale: 1, opacity: 1, y: 0 }}
                    exit={{ scale: 0.95, opacity: 0, y: 20 }}
                    className="bg-theme-card relative z-10 w-full max-w-md p-8 rounded-3xl shadow-2xl border border-theme-border-soft text-center"
                  >
                    <div className="w-16 h-16 mx-auto bg-[image:var(--accent-gradient)] rounded-2xl flex items-center justify-center mb-6 shadow-glow">
                      <Lock className="w-8 h-8 text-white" />
                    </div>
                    <h2 className="text-2xl font-black text-theme-primary mb-2">Limit Reached</h2>
                    <p className="text-sm font-semibold text-theme-muted mb-6">
                      You've hit your free tier limit of {settings?.freeInvoiceLimit || 15} invoices. Upgrade to the Premium Plan for unlimited invoicing and exclusive SaaS features.
                    </p>
                    <div className="space-y-3">
                      <button
                        onClick={() => {
                          setShowPaywallModal(false);
                          setCurrentTab('subscription');
                        }}
                        className="w-full py-3.5 bg-[image:var(--accent-gradient)] text-white font-black uppercase tracking-wider rounded-xl hover:opacity-90 transition-all shadow-md active:scale-95"
                      >
                        Upgrade Now
                      </button>
                      <button
                        onClick={() => setShowPaywallModal(false)}
                        className="w-full py-3.5 bg-transparent border border-theme-border-soft text-theme-muted font-bold rounded-xl hover:text-theme-primary hover:bg-theme-surface transition-all active:scale-95"
                      >
                        Not Right Now
                      </button>
                    </div>
                  </motion.div>
                </div>
              )}
            </AnimatePresence>
          </motion.div>
        )}
      </AnimatePresence>
      {showConfetti && (
        <Confetti 
          width={window.innerWidth} 
          height={window.innerHeight} 
          recycle={false} 
          numberOfPieces={300} 
          gravity={0.15} 
          style={{ zIndex: 100000, position: 'fixed', top: 0, left: 0 }} 
        />
      )}
      <CommandPalette 
        isOpen={showCommandPalette} 
        onClose={() => setShowCommandPalette(false)} 
        onNavigate={(action) => {
          if (action.openQuickBill) {
            setIsQuickBillOpen(true);
          } else if (action.tab) {
            setCurrentTab(action.tab);
          }
        }} 
      />
    </ErrorBoundary>
  );
}

export default App;
